= Presets for TypeScript
:experimental:
:source-highlighter: highlight.js

This package provides predefined, opinionated https://www.typescriptlang.org[TypeScript] configuration.

== Installation
Install the `@rainstormy/preset-typescript` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/preset-typescript typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/preset-typescript typescript
----

[source,shell]
----
yarn add --dev @rainstormy/preset-typescript typescript
----

== Usage
Create a https://www.typescriptlang.org/tsconfig[TypeScript configuration file] (`tsconfig.json`) and extend the following configurations to enable type-checking and optionally also generation of `js` and `d.ts` files:

* `@rainstormy/preset-typescript/check`
* `@rainstormy/preset-typescript/generate` (to generate `js` and `d.ts` files)
* `@rainstormy/preset-typescript/generate-types` (to generate `d.ts` files only)
* `@rainstormy/preset-typescript/target-node-es2023` (for Node.js projects)
* `@rainstormy/preset-typescript/target-web-es2023` (for web browser projects)

For example:

[source,json]
----
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"extends": [
		"@rainstormy/preset-typescript/check",
		"@rainstormy/preset-typescript/target-web-es2023"
	]
}
----

[TIP]
.Override Settings
====
To override the settings configured by this preset, specify the desired options after the `extends` field to take precedence over the preset.
For example:

[source,json]
----
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"extends": [
		"@rainstormy/preset-typescript/check",
		"@rainstormy/preset-typescript/generate",
		"@rainstormy/preset-typescript/target-node-es2023"
	],
	"compilerOptions": {
		"baseUrl": "./",
		"incremental": true,
		"noEmitOnError": false,
		"outDir": "dist",
		"sourceMap": true
	},
	"include": ["./src/**/*.ts", "./*.config.js", "./*.config.ts"]
}
----
====

== Complementary Presets
* https://github.com/rainstormy/presets-web/tree/main/packages/preset-eslint-base[@rainstormy/preset-eslint-base]
* https://github.com/rainstormy/presets-web/tree/main/packages/preset-prettier-base[@rainstormy/preset-prettier-base]
