= Presets for Web Projects
:experimental:
:source-highlighter: highlight.js

This repository contains predefined, opinionated tooling configurations for web projects.

== https://eslint.org[ESLint]

[[eslint_basic]]
=== Basic Configuration

. Install the `@rainstormy/preset-eslint-base` package and its peer dependencies:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-base
$ npm install --save-dev eslint
$ npm install --save-dev typescript
----

. Define an https://eslint.org/docs/latest/use/configure[ESLint configuration file]:
+
[source,javascript]
----
// eslint.config.js

import {
	eslintAmbientTypeScriptModules,
	eslintBase
} from "@rainstormy/preset-eslint-base"

export default [
	eslintBase({
		files: ["**/*.+(js|ts)"],
		tsconfig: "./tsconfig.json",
	}),
	eslintAmbientTypeScriptModules({
		files: ["**/*.d.ts"],
	}),
]
----

[TIP]
.Ignore Patterns
====
To exclude certain files and directories from linting, add an extra configuration at the beginning of the array:

[source,javascript]
----
// eslint.config.js

export default [
	{
		ignores: [
			"coverage/**",
			"dist/**",
		],
	},
	// eslintBase({ ... }),
	// etc.
]
----
====

[[eslint_next]]
=== Configuration for https://nextjs.org/[Next.js]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-next` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-next
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintNext } from "@rainstormy/preset-eslint-next"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintNext({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

[[eslint_preact]]
=== Configuration for https://preactjs.com[Preact]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-preact` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-preact
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintPreact } from "@rainstormy/preset-eslint-preact"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintPreact({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

CAUTION: The Preact preset includes `@rainstormy/preset-eslint-jsx`.

[[eslint_react]]
=== Configuration for https://react.dev[React]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-react` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-react
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintReact } from "@rainstormy/preset-eslint-react"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintReact({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

CAUTION: The React preset includes `@rainstormy/preset-eslint-jsx`.

[[eslint_solid]]
=== Configuration for https://www.solidjs.com[Solid]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-solid` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-solid
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintSolid } from "@rainstormy/preset-eslint-solid"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintSolid({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

CAUTION: The Solid preset includes `@rainstormy/preset-eslint-jsx`.

[[eslint_jsx]]
=== Configuration for Other JSX Frameworks

The JSX preset is intended to be used as a foundation for other JSX-based frameworks such as https://qwik.builder.io[Qwik].

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-jsx` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-jsx
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintJsx } from "@rainstormy/preset-eslint-jsx"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintJsx({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

. Install other relevant ESLint plugins and configure them accordingly, for example:
+
[source,javascript]
----
// eslint.config.js

import qwikPlugin from "eslint-plugin-qwik"

export default [
	// eslintBase({ ... }),
	// eslintJsx({ ... }),
	// etc.
	{
		files: ["**/*.+(jsx|tsx)"],
		plugins: {
			qwik: qwikPlugin,
		},
		rules: {
			"react/function-component-definition": "off",
			"react/jsx-key": "off",
			"react/jsx-no-script-url": "off",
			"qwik/jsx-img": "error",
			"qwik/jsx-key": "error",
			"qwik/jsx-no-script-url": "error",
			"qwik/loader-location": "error",
			"qwik/no-react-props": "error",
			"qwik/prefer-classlist": "error",
			"qwik/unused-server": "error",
			"qwik/use-method-usage": "error",
			"qwik/valid-lexical-scope": "error",
			// etc.
		},
	}
]
----

[CAUTION]
====
The JSX preset is already included in:

* `@rainstormy/preset-eslint-preact`
* `@rainstormy/preset-eslint-react`
* `@rainstormy/preset-eslint-solid`
====

[[eslint_storybook]]
=== Configuration for https://storybook.js.org[Storybook]

. Follow the instructions in one of the JSX presets, e.g. <<eslint_react>>.
. Install the `@rainstormy/preset-eslint-storybook` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-storybook
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets stories and Storybook configuration files:
+
[source,javascript]
----
// eslint.config.js

import { eslintStorybook } from "@rainstormy/preset-eslint-storybook"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintStorybook({
		files: [
			".storybook/**/*.+(js|jsx|ts|tsx)",
			"**/*.stories.+(js|jsx|ts|tsx)"
		],
	}),
]
----

[[eslint_tailwind]]
=== Configuration for https://tailwindcss.com[Tailwind CSS]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-tailwind` package and its peer dependencies:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-tailwind
$ npm install --save-dev tailwindcss
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets JSX component files:
+
[source,javascript]
----
// eslint.config.js

import { eslintTailwind } from "@rainstormy/preset-eslint-tailwind"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintTailwind({
		files: ["**/*.+(jsx|tsx)"],
	}),
]
----

[[eslint_testing_library]]
=== Configuration for https://testing-library.com[Testing Library]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-testing-library` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-testing-library
----

. Add a new configuration to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that targets component test files:
+
[source,javascript]
----
// eslint.config.js

import { eslintTestingLibrary } from "@rainstormy/preset-eslint-testing-library"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintTestingLibrary({
		files: ["**/*.+(spec|test).+(jsx|tsx)"],
	}),
]
----

[[eslint_vitest]]
=== Configuration for https://vitest.dev[Vitest]

. Follow the instructions in <<eslint_basic>>.
. Install the `@rainstormy/preset-eslint-vitest` package and its peer dependencies:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-eslint-vitest
$ npm install --save-dev vitest
----

. Add new configurations to the https://eslint.org/docs/latest/use/configure[ESLint configuration file] that target test files:
+
[source,javascript]
----
// eslint.config.js

import { eslintTestData } from "@rainstormy/preset-eslint-base"
import { eslintVitest } from "@rainstormy/preset-eslint-vitest"

export default [
	// eslintBase({ ... }),
	// etc.
	eslintTestData({
		files: ["**/*.+(spec|test).+(js|jsx|ts|tsx)"],
	}),
	eslintVitest({
		files: ["**/*.+(spec|test).+(js|jsx|ts|tsx)"],
	}),
]
----

== https://prettier.io[Prettier]

[[prettier_basic]]
=== Basic Configuration

. Install the `@rainstormy/preset-prettier-base` package and its peer dependencies:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-prettier-base
$ npm install --save-dev prettier
$ npm install --save-dev typescript
----

. Define a https://prettier.io/docs/en/configuration.html[Prettier configuration file]:
+
[source,javascript]
----
// prettier.config.js

import { prettierBase } from "@rainstormy/preset-prettier-base"

export default prettierBase()
----

[[prettier_tailwind]]
=== Configuration for https://tailwindcss.com[Tailwind CSS]

. Follow the instructions in <<prettier_basic>>.
. Install the `@rainstormy/preset-prettier-tailwind` package:
+
[source,shell]
----
$ npm install --save-dev @rainstormy/preset-prettier-tailwind
----

. Apply the Tailwind CSS configuration as the last one in the https://prettier.io/docs/en/configuration.html[Prettier configuration file]:
+
[source,javascript]
----
// prettier.config.js

import { prettierBase, prettierMergeConfigs } from "@rainstormy/preset-prettier-base"
import { prettierTailwind } from "@rainstormy/preset-prettier-tailwind"

export default prettierMergeConfigs([
    prettierBase(),
	prettierTailwind(),
])
----

== Contributing

Please take a look at link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] for detailed instructions on how to contribute to this project 😀
