import { isAcceptedOxlintRule, normaliseOxlintRule } from "#oxlint/utilities/OxlintRule.ts"

/**
 * Rule table contents, copied directly from the web page.
 *
 * @see https://oxc.rs/docs/guide/usage/linter/rules.html
 */
const RAW_OXLINT_RULE_TABLE = `
accessor-pairs\teslint\tpedantic\t\t\tv1.33.0
adjacent-overload-signatures\ttypescript\tstyle\t\t\tv0.0.7
alt-text\tjsx-a11y\tcorrectness\t\t\tv0.0.16
always-return\tpromise\tsuspicious\t\t\tv1.13.0
anchor-ambiguous-text\tjsx-a11y\trestriction\t\t\tv0.13.2
anchor-has-content\tjsx-a11y\tcorrectness\t\t💡\tv0.0.18
anchor-is-valid\tjsx-a11y\tcorrectness\t\t\tv0.0.19
approx-constant\toxc\tsuspicious\t\t💡\tv0.1.1
aria-activedescendant-has-tabindex\tjsx-a11y\tcorrectness\t\t\tv0.2.1
aria-props\tjsx-a11y\tcorrectness\t\t🛠️\tv0.0.22
aria-proptypes\tjsx-a11y\tcorrectness\t\t\tv1.36.0
aria-role\tjsx-a11y\tcorrectness\t\t\tv0.1.1
aria-unsupported-elements\tjsx-a11y\tcorrectness\t\t🛠️\tv0.1.1
array-callback-return\teslint\tpedantic\t\t🚧\tv0.0.3
array-type\ttypescript\tstyle\t\t🛠️\tv0.2.8
arrow-body-style\teslint\tstyle\t\t🛠️\tv1.4.0
autocomplete-valid\tjsx-a11y\tcorrectness\t\t\tv0.2.0
avoid-new\tpromise\tstyle\t\t\tv0.6.1
await-thenable💭\ttypescript\tcorrectness\t✅\t💡\tv1.12.0
bad-array-method-on-arguments\toxc\tcorrectness\t✅\t\tv0.0.3
bad-bitwise-operator\toxc\trestriction\t\t💡\tv0.0.3
bad-char-at-comparison\toxc\tcorrectness\t✅\t\tv0.0.22
bad-comparison-sequence\toxc\tcorrectness\t✅\t\tv0.0.3
bad-min-max-func\toxc\tcorrectness\t✅\t\tv0.0.3
bad-object-literal-comparison\toxc\tcorrectness\t✅\t\tv0.1.1
bad-replace-all-arg\toxc\tcorrectness\t✅\t\tv0.0.22
ban-ts-comment\ttypescript\tpedantic\t\t🛠️\tv0.0.8
ban-tslint-comment\ttypescript\tstyle\t\t🛠️\tv0.2.9
ban-types\ttypescript\tpedantic\t\t\tv0.0.14
block-scoped-var\teslint\tsuspicious\t\t\tv0.16.9
branches-sharing-code\toxc\tpedantic\t\t💡\tv1.22.0
button-has-type\treact\trestriction\t\t\tv0.1.1
callback-return\tnode\tstyle\t\t\tv1.67.0
capitalized-comments\teslint\tstyle\t\t🛠️\tv1.34.0
catch-error-name\tunicorn\tstyle\t\t🛠️\tv0.0.14
catch-or-return\tpromise\trestriction\t\t\tv0.9.2
check-access\tjsdoc\trestriction\t\t\tv0.2.16
check-property-names\tjsdoc\tcorrectness\t\t🚧\tv0.2.18
check-tag-names\tjsdoc\tcorrectness\t\t🚧\tv0.3.2
checked-requires-onchange-or-readonly\treact\tpedantic\t\t\tv0.2.15
class-literal-property-style\ttypescript\tstyle\t\t🚧\tv1.47.0
class-methods-use-this\teslint\trestriction\t\t\tv1.16.0
click-events-have-key-events\tjsx-a11y\tcorrectness\t\t\tv0.2.1
complexity\teslint\trestriction\t\t\tv1.37.0
component-definition-name-casing\tvue\tstyle\t\t🛠️\tv1.68.0
consistent-assert\tunicorn\tpedantic\t\t🛠️\tv0.16.9
consistent-date-clone\tunicorn\tstyle\t\t🛠️\tv0.15.13
consistent-each-for\tvitest\tcorrectness\t\t\tv1.39.0
consistent-empty-array-spread\tunicorn\tpedantic\t\t💡\tv0.10.1
consistent-existence-index-check\tunicorn\tstyle\t\t🛠️\tv0.12.0
consistent-function-scoping\tunicorn\tsuspicious\t\t🚧\tv0.8.0
consistent-generic-constructors\ttypescript\tstyle\t\t🛠️\tv0.14.0
consistent-indexed-object-style\ttypescript\tstyle\t\t🛠️\tv0.4.2
consistent-return💭\ttypescript\tsuspicious\t\t\tv0.0.8
consistent-template-literal-escape\tunicorn\tstyle\t\t🛠️\tv1.60.0
consistent-test-filename\tvitest\tstyle\t\t\tv1.36.0
consistent-test-it\tjest\tstyle\t\t🛠️\tv0.5.3
consistent-test-it\tvitest\tstyle\t\t🛠️\tv0.5.3
consistent-type-assertions\ttypescript\tstyle\t\t🛠️ 💡\tv1.44.0
consistent-type-definitions\ttypescript\tstyle\t\t⚠️ 🛠️\tv0.2.17
consistent-type-exports💭\ttypescript\tstyle\t\t\tv0.0.8
consistent-type-imports\ttypescript\tstyle\t\t🛠️\tv0.5.2
consistent-type-specifier-style\timport\tstyle\t\t🛠️\tv0.16.11
consistent-vitest-vi\tvitest\tstyle\t\t🛠️\tv1.37.0
const-comparisons\toxc\tcorrectness\t✅\t\tv0.0.22
constructor-super\teslint\tcorrectness\t✅\t\tv0.0.3
control-has-associated-label\tjsx-a11y\tcorrectness\t\t\tv1.65.0
curly\teslint\tstyle\t\t🛠️\tv0.15.13
custom-error-definition\tunicorn\tstyle\t\t🚧\tv1.57.0
default\timport\tcorrectness\t\t\tv0.0.13
default-case\teslint\trestriction\t\t\tv0.4.0
default-case-last\teslint\tstyle\t\t\tv0.0.16
default-param-last\teslint\tstyle\t\t\tv0.2.15
define-emits-declaration\tvue\tstyle\t\t🚧\tv1.15.0
define-props-declaration\tvue\tstyle\t\t\tv1.15.0
define-props-destructuring\tvue\tstyle\t\t\tv1.20.0
display-name\treact\tpedantic\t\t\tv1.42.0
dot-notation💭\ttypescript\tstyle\t\t\tv1.49.0
double-comparisons\toxc\tcorrectness\t✅\t💡\tv0.0.22
empty-brace-spaces\tunicorn\tstyle\t\t🛠️\tv0.0.18
empty-tags\tjsdoc\trestriction\t\t🚧\tv0.2.16
eqeqeq\teslint\tpedantic\t\t⚠️ 🛠️\tv0.0.3
erasing-op\toxc\tcorrectness\t✅\t⚠️ 🛠️\tv0.1.1
error-message\tunicorn\tstyle\t\t\tv0.0.14
escape-case\tunicorn\tpedantic\t\t🛠️\tv0.0.19
exhaustive-deps\treact\tcorrectness\t\t⚠️ 🛠 💡\tv0.12.0
expect-expect\tjest\tcorrectness\t\t\tv0.0.12
expect-expect\tvitest\tcorrectness\t\t\tv0.0.12
explicit-function-return-type\ttypescript\trestriction\t\t\tv0.4.4
explicit-length-check\tunicorn\tpedantic\t\t🛠️\tv0.0.19
explicit-member-accessibility\ttypescript\trestriction\t\t🛠️ 💡\tv1.61.0
explicit-module-boundary-types\ttypescript\trestriction\t\t\tv1.9.0
export\timport\tnursery\t\t\tv0.0.21
exports-last\timport\tstyle\t\t\tv0.15.14
extensions\timport\trestriction\t\t\tv1.2.0
filename-case\tunicorn\tstyle\t\t\tv0.0.14
first\timport\tstyle\t\t🚧\tv0.11.1
for-direction\teslint\tcorrectness\t✅\t⚠️ 🛠️\tv0.0.3
forbid-component-props\treact\trestriction\t\t\tv1.62.0
forbid-dom-props\treact\trestriction\t\t\tv1.24.0
forbid-elements\treact\trestriction\t\t\tv0.16.11
forward-ref-uses-ref\treact\tcorrectness\t\t💡\tv0.16.9
func-name-matching\teslint\tstyle\t\t\tv1.62.0
func-names\teslint\tstyle\t\t🛠️ 💡\tv0.7.0
func-style\teslint\tstyle\t\t🚧\tv0.15.11
getter-return\teslint\tcorrectness\t✅\t\tv0.0.3
global-require\tnode\tstyle\t\t\tv1.36.0
google-font-display\tnextjs\tcorrectness\t\t\tv0.2.0
google-font-preconnect\tnextjs\tcorrectness\t\t\tv0.2.0
group-exports\timport\tstyle\t\t\tv0.16.6
grouped-accessor-pairs\teslint\tstyle\t\t🚧\tv0.15.12
guard-for-in\teslint\tstyle\t\t\tv0.2.14
handle-callback-err\tnode\trestriction\t\t\tv1.56.0
heading-has-content\tjsx-a11y\tcorrectness\t\t\tv0.0.19
hoisted-apis-on-top\tvitest\tcorrectness\t\t💡\tv1.39.0
hook-use-state\treact\tstyle\t\t🚧\tv1.59.0
html-has-lang\tjsx-a11y\tcorrectness\t\t\tv0.0.18
id-length\teslint\tstyle\t\t\tv1.4.0
id-match\teslint\tstyle\t\t\tv1.66.0
iframe-has-title\tjsx-a11y\tcorrectness\t\t\tv0.0.19
iframe-missing-sandbox\treact\tsuspicious\t\t🚧\tv0.10.0
img-redundant-alt\tjsx-a11y\tcorrectness\t\t\tv0.0.19
implements-on-classes\tjsdoc\tcorrectness\t\t\tv0.3.2
import-style\tunicorn\trestriction\t\t\tv1.67.0
init-declarations\teslint\tstyle\t\t\tv0.15.11
inline-script-id\tnextjs\tcorrectness\t\t\tv0.2.0
interactive-supports-focus\tjsx-a11y\tcorrectness\t\t💡\tv1.63.0
jsx-boolean-value\treact\tstyle\t\t🛠️\tv0.7.0
jsx-curly-brace-presence\treact\tstyle\t\t🛠️\tv0.7.0
jsx-filename-extension\treact\trestriction\t\t🚧\tv0.15.14
jsx-fragments\treact\tstyle\t\t🛠️\tv1.12.0
jsx-handler-names\treact\tstyle\t\t\tv1.13.0
jsx-key\treact\tcorrectness\t\t\tv0.0.14
jsx-max-depth\treact\tstyle\t\t\tv1.36.0
jsx-no-comment-textnodes\treact\tsuspicious\t\t\tv0.0.14
jsx-no-constructed-context-values\treact\tperf\t\t\tv1.48.0
jsx-no-duplicate-props\treact\tcorrectness\t\t\tv0.0.14
jsx-no-jsx-as-prop\treact-perf\tperf\t\t\tv0.2.3
jsx-no-new-array-as-prop\treact-perf\tperf\t\t\tv0.2.3
jsx-no-new-function-as-prop\treact-perf\tperf\t\t\tv0.2.3
jsx-no-new-object-as-prop\treact-perf\tperf\t\t\tv0.2.3
jsx-no-script-url\treact\tsuspicious\t\t🚧\tv0.13.2
jsx-no-target-blank\treact\tpedantic\t\t🚧\tv0.2.5
jsx-no-undef\treact\tcorrectness\t\t\tv0.1.1
jsx-no-useless-fragment\treact\tpedantic\t\t💡\tv0.0.14
jsx-pascal-case\treact\tstyle\t\t\tv1.19.0
jsx-props-no-spread-multi\treact\tcorrectness\t\t🛠️\tv0.7.2
jsx-props-no-spreading\treact\tstyle\t\t\tv1.33.0
label-has-associated-control\tjsx-a11y\tcorrectness\t\t\tv0.9.1
lang\tjsx-a11y\tcorrectness\t\t\tv0.1.1
logical-assignment-operators\teslint\tstyle\t\t🚧\tv1.63.0
max-classes-per-file\teslint\tpedantic\t\t\tv0.3.4
max-dependencies\timport\tpedantic\t\t\tv0.5.0
max-depth\teslint\tpedantic\t\t\tv0.15.12
max-expects\tjest\tstyle\t\t\tv0.0.18
max-expects\tvitest\tstyle\t\t\tv0.0.18
max-lines\teslint\tpedantic\t\t\tv0.2.14
max-lines-per-function\teslint\tpedantic\t\t\tv0.15.12
max-nested-callbacks\teslint\tpedantic\t\t\tv0.15.12
max-nested-describe\tjest\tstyle\t\t\tv0.4.4
max-nested-describe\tvitest\tstyle\t\t\tv0.4.4
max-params\teslint\tstyle\t\t\tv0.2.14
max-props\tvue\trestriction\t\t\tv1.19.0
max-statements\teslint\tstyle\t\t\tv1.35.0
media-has-caption\tjsx-a11y\tcorrectness\t\t\tv0.1.1
method-signature-style\ttypescript\tstyle\t\t🚧\tv1.68.0
misrefactored-assign-op\toxc\tsuspicious\t\t💡\tv0.1.1
missing-throw\toxc\tcorrectness\t✅\t💡\tv0.0.3
mouse-events-have-key-events\tjsx-a11y\tcorrectness\t\t\tv0.1.1
named\timport\tnursery\t\t\tv0.0.13
namespace\timport\tcorrectness\t\t\tv0.2.11
new-cap\teslint\tstyle\t\t🚧\tv0.15.5
new-for-builtins\tunicorn\tpedantic\t\t🚧\tv0.0.16
newline-after-import\timport\tstyle\t\t🛠️\tv1.66.0
next-script-for-ga\tnextjs\tcorrectness\t\t\tv0.2.0
next-tick-style\tvue\tstyle\t\t🛠️\tvnext
no-absolute-path\timport\tsuspicious\t\t🚧\tv0.15.13
no-abusive-eslint-disable\tunicorn\trestriction\t\t\tv0.0.18
no-access-key\tjsx-a11y\tcorrectness\t\t💡\tv0.0.21
no-accessor-recursion\tunicorn\tsuspicious\t\t\tv0.16.5
no-accumulating-spread\toxc\tperf\t\t\tv0.0.19
no-alert\teslint\trestriction\t\t\tv0.9.3
no-alias-methods\tjest\tstyle\t\t🛠️\tv0.0.12
no-alias-methods\tvitest\tstyle\t\t🛠️\tv0.0.12
no-amd\timport\trestriction\t\t\tv0.0.16
no-anonymous-default-export\timport\tstyle\t\t\tv0.15.14
no-anonymous-default-export\tunicorn\trestriction\t\t🚧\tv0.3.3
no-aria-hidden-on-focusable\tjsx-a11y\tcorrectness\t\t🛠️\tv0.0.22
no-array-callback-reference\tunicorn\tpedantic\t\t🚧\tv1.19.0
no-array-constructor\teslint\tpedantic\t\t🛠️\tv0.0.3
no-array-delete💭\ttypescript\tcorrectness\t✅\t💡\tv1.12.0
no-array-for-each\tunicorn\trestriction\t\t🚧\tv0.0.19
no-array-index-key\treact\tperf\t\t\tv0.13.0
no-array-method-this-argument\tunicorn\tstyle\t\t🚧\tv0.16.12
no-array-reduce\tunicorn\trestriction\t\t\tv0.0.19
no-array-reverse\tunicorn\tsuspicious\t\t🛠️\tv1.15.0
no-array-sort\tunicorn\tsuspicious\t\t🛠️\tv1.15.0
no-arrow-functions-in-watch\tvue\tcorrectness\t\t\tv1.39.0
no-assign-module-variable\tnextjs\tcorrectness\t\t\tv0.2.0
no-async-await\toxc\trestriction\t\t\tv0.4.2
no-async-client-component\tnextjs\tcorrectness\t\t\tv0.2.0
no-async-endpoint-handlers\toxc\tsuspicious\t\t\tv0.9.2
no-async-promise-executor\teslint\tcorrectness\t✅\t\tv0.0.3
no-autofocus\tjsx-a11y\tcorrectness\t\t💡\tv0.0.19
no-await-expression-member\tunicorn\tstyle\t\t⚠️ 🛠️\tv0.0.19
no-await-in-loop\teslint\tperf\t\t\tv0.3.2
no-await-in-promise-methods\tunicorn\tcorrectness\t✅\t💡\tv0.2.18
no-barrel-file\toxc\trestriction\t\t\tv0.3.0
no-base-to-string💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
no-before-interactive-script-outside-document\tnextjs\tcorrectness\t\t\tv0.2.7
no-bitwise\teslint\trestriction\t\t\tv0.0.3
no-callback-in-promise\tpromise\tcorrectness\t\t\tv0.10.0
no-caller\teslint\tcorrectness\t✅\t\tv0.0.3
no-case-declarations\teslint\tpedantic\t\t💡\tv0.0.4
no-children-prop\treact\tcorrectness\t\t\tv0.0.14
no-class-assign\teslint\tcorrectness\t✅\t\tv0.0.3
no-clone-element\treact\trestriction\t\t\tv1.53.0
no-commented-out-tests\tjest\tsuspicious\t\t\tv0.0.8
no-commented-out-tests\tvitest\tsuspicious\t\t\tv0.0.8
no-commonjs\timport\trestriction\t\t\tv0.11.0
no-compare-neg-zero\teslint\tcorrectness\t✅\t🛠️ 💡\tv0.0.3
no-computed-properties-in-data\tvue\tcorrectness\t\t\tv1.67.0
no-cond-assign\teslint\tcorrectness\t✅\t\tv0.0.5
no-conditional-expect\tjest\tcorrectness\t\t\tv0.0.12
no-conditional-expect\tvitest\tcorrectness\t\t\tv0.0.12
no-conditional-in-test\tjest\tpedantic\t\t\tv0.8.0
no-conditional-in-test\tvitest\tpedantic\t\t\tv0.8.0
no-conditional-tests\tvitest\tcorrectness\t\t\tv0.8.0
no-confusing-non-null-assertion\ttypescript\tsuspicious\t\t🚧\tv0.6.1
no-confusing-set-timeout\tjest\tstyle\t\t\tv0.0.14
no-confusing-void-expression💭\ttypescript\tpedantic\t\t🛠️ 💡\tv1.12.0
no-console\teslint\trestriction\t\t💡\tv0.0.13
no-console-spaces\tunicorn\tstyle\t\t🛠️\tv0.0.14
no-const-assign\teslint\tcorrectness\t✅\t\tv0.0.3
no-const-enum\toxc\trestriction\t\t🛠️\tv0.4.2
no-constant-binary-expression\teslint\tcorrectness\t✅\t\tv0.0.3
no-constant-condition\teslint\tcorrectness\t✅\t\tv0.0.3
no-constructor-return\teslint\tpedantic\t\t\tv0.4.3
no-continue\teslint\tstyle\t\t\tv0.2.14
no-control-regex\teslint\tcorrectness\t✅\t\tv0.0.7
no-css-tags\tnextjs\tcorrectness\t\t\tv0.2.0
no-cycle\timport\trestriction\t\t\tv0.0.13
no-danger\treact\trestriction\t\t\tv0.0.14
no-danger-with-children\treact\tcorrectness\t\t\tv0.9.6
no-debugger\teslint\tcorrectness\t✅\t💡\tv0.0.3
no-default-export\timport\trestriction\t\t\tv0.2.14
no-defaults\tjsdoc\tcorrectness\t\t🚧\tv0.3.2
no-delete-var\teslint\tcorrectness\t✅\t\tv0.0.4
no-deprecated💭\ttypescript\tpedantic\t\t\tv1.26.0
no-deprecated-data-object-declaration\tvue\tcorrectness\t\t🚧\tv1.62.0
no-deprecated-delete-set\tvue\tcorrectness\t\t\tv1.62.0
no-deprecated-destroyed-lifecycle\tvue\tcorrectness\t\t🛠️\tv1.35.0
no-deprecated-events-api\tvue\tcorrectness\t\t\tv1.62.0
no-deprecated-functions\tjest\tstyle\t\t🛠️\tv0.0.18
no-deprecated-model-definition\tvue\tcorrectness\t\t🚧\tv1.63.0
no-deprecated-props-default-this\tvue\tcorrectness\t\t🚧\tv1.67.0
no-deprecated-vue-config-keycodes\tvue\tcorrectness\t\t\tv1.62.0
no-did-mount-set-state\treact\tcorrectness\t\t\tv1.36.0
no-did-update-set-state\treact\tcorrectness\t\t\tv1.62.0
no-direct-mutation-state\treact\tcorrectness\t\t\tv0.2.0
no-disabled-tests\tjest\tcorrectness\t\t\tv0.0.7
no-disabled-tests\tvitest\tcorrectness\t\t\tv0.0.7
no-distracting-elements\tjsx-a11y\tcorrectness\t\t\tv0.0.22
no-div-regex\teslint\trestriction\t\t🛠️\tv0.4.2
no-document-cookie\tunicorn\trestriction\t\t\tv0.0.18
no-document-import-in-page\tnextjs\tcorrectness\t\t\tv0.2.1
no-done-callback\tjest\tstyle\t\t🚧\tv0.0.13
no-dupe-class-members\teslint\tcorrectness\t✅\t\tv0.0.3
no-dupe-else-if\teslint\tcorrectness\t✅\t\tv0.0.5
no-dupe-keys\teslint\tcorrectness\t✅\t\tv0.0.3
no-duplicate-case\teslint\tcorrectness\t✅\t\tv0.0.3
no-duplicate-enum-values\ttypescript\tcorrectness\t✅\t\tv0.0.8
no-duplicate-head\tnextjs\tcorrectness\t\t\tv0.3.3
no-duplicate-hooks\tjest\tstyle\t\t\tv0.4.0
no-duplicate-hooks\tvitest\tstyle\t\t\tv0.4.0
no-duplicate-imports\teslint\tstyle\t\t🚧\tv0.13.2
no-duplicate-type-constituents💭\ttypescript\tcorrectness\t✅\t🛠️\tv1.12.0
no-duplicates\timport\tstyle\t\t\tv0.2.11
no-dynamic-delete\ttypescript\trestriction\t\t\tv0.5.2
no-dynamic-require\timport\trestriction\t\t\tv0.9.3
no-else-return\teslint\tpedantic\t\t🛠️\tv0.9.10
no-empty\teslint\trestriction\t\t💡\tv0.0.3
no-empty-character-class\teslint\tcorrectness\t✅\t\tv0.0.7
no-empty-file\tunicorn\tcorrectness\t✅\t\tv0.0.15
no-empty-function\teslint\trestriction\t\t💡\tv0.3.3
no-empty-interface\ttypescript\tstyle\t\t🚧\tv0.0.6
no-empty-named-blocks\timport\tsuspicious\t\t🛠️\tv0.16.1
no-empty-object-type\ttypescript\trestriction\t\t🚧\tv0.12.0
no-empty-pattern\teslint\tcorrectness\t✅\t\tv0.0.3
no-empty-static-block\teslint\tcorrectness\t✅\t💡\tv0.0.19
no-eq-null\teslint\trestriction\t\t⚠️ 🛠️\tv0.2.14
no-eval\teslint\tcorrectness\t✅\t\tv0.0.3
no-ex-assign\teslint\tcorrectness\t✅\t\tv0.0.4
no-explicit-any\ttypescript\trestriction\t\t🛠️\tv0.0.13
no-export\tjest\tcorrectness\t\t\tv0.0.13
no-export-in-script-setup\tvue\tcorrectness\t\t\tv1.20.0
no-exports-assign\tnode\tstyle\t\t🛠️\tv0.9.3
no-expose-after-await\tvue\tcorrectness\t\t\tv1.67.0
no-extend-native\teslint\tsuspicious\t\t\tv0.9.7
no-extra-bind\teslint\tsuspicious\t\t🚧\tv1.1.0
no-extra-boolean-cast\teslint\tcorrectness\t✅\t🛠️ 💡\tv0.0.8
no-extra-label\teslint\tstyle\t\t🛠️\tv0.15.4
no-extra-non-null-assertion\ttypescript\tcorrectness\t✅\t🛠️\tv0.0.6
no-extraneous-class\ttypescript\tsuspicious\t\t⚠️ 💡\tv0.7.0
no-fallthrough\teslint\tpedantic\t\t🚧\tv0.0.14
no-find-dom-node\treact\tcorrectness\t\t\tv0.0.15
no-floating-promises💭\ttypescript\tcorrectness\t✅\t💡\tv1.11.0
no-focused-tests\tjest\tcorrectness\t\t💡\tv0.0.8
no-focused-tests\tvitest\tcorrectness\t\t💡\tv0.0.8
no-for-in-array💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
no-func-assign\teslint\tcorrectness\t✅\t\tv0.0.3
no-global-assign\teslint\tcorrectness\t✅\t\tv0.0.7
no-head-element\tnextjs\tcorrectness\t\t\tv0.2.1
no-head-import-in-document\tnextjs\tcorrectness\t\t\tv0.2.0
no-hex-escape\tunicorn\tpedantic\t\t🛠️\tv0.0.18
no-hooks\tjest\tstyle\t\t\tv0.0.16
no-hooks\tvitest\tstyle\t\t\tv0.0.16
no-html-link-for-pages\tnextjs\tcorrectness\t\t\tv1.7.0
no-identical-title\tjest\tstyle\t\t\tv0.0.14
no-identical-title\tvitest\tstyle\t\t\tv0.0.14
no-img-element\tnextjs\tcorrectness\t\t🚧\tv0.2.0
no-immediate-mutation\tunicorn\tpedantic\t\t🚧\tv1.35.0
no-implicit-coercion\teslint\tstyle\t\t🛠️\tv1.33.0
no-implicit-globals\teslint\trestriction\t\t\tv1.65.0
no-implied-eval\teslint\tsuspicious\t✅\t\tv1.66.0
no-implied-eval💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
no-import-assign\teslint\tcorrectness\t✅\t\tv0.0.5
no-import-compiler-macros\tvue\trestriction\t\t⚠️ 🛠️\tv1.21.0
no-import-node-test\tvitest\tstyle\t\t💡\tv0.7.0
no-import-type-side-effects\ttypescript\trestriction\t\t🛠️\tv0.5.0
no-importing-vitest-globals\tvitest\tstyle\t\t🛠️\tv1.49.0
no-inferrable-types\ttypescript\tstyle\t\t💡\tv0.14.0
no-inline-comments\teslint\tpedantic\t\t\tv1.34.0
no-inner-declarations\teslint\tpedantic\t\t\tv0.0.5
no-instanceof-array\tunicorn\tpedantic\t\t🛠️\tv0.0.8
no-instanceof-builtins\tunicorn\tsuspicious\t\t💡\tv0.16.12
no-interactive-element-to-noninteractive-role\tjsx-a11y\tcorrectness\t\t\tv1.65.0
no-interpolation-in-snapshots\tjest\tstyle\t\t\tv0.0.13
no-interpolation-in-snapshots\tvitest\tstyle\t\t\tv0.0.13
no-invalid-fetch-options\tunicorn\tcorrectness\t✅\t\tv0.15.12
no-invalid-regexp\teslint\tcorrectness\t✅\t\tv0.9.4
no-invalid-remove-event-listener\tunicorn\tcorrectness\t✅\t\tv0.0.16
no-invalid-void-type\ttypescript\trestriction\t\t\tv1.47.0
no-irregular-whitespace\teslint\tcorrectness\t✅\t\tv0.1.1
no-is-mounted\treact\tcorrectness\t\t\tv0.0.19
no-iterator\teslint\tcorrectness\t✅\t💡\tv0.2.15
no-jasmine-globals\tjest\tstyle\t\t🛠️\tv0.0.13
no-label-var\teslint\tstyle\t\t\tv0.6.0
no-labels\teslint\tstyle\t\t\tv0.15.4
no-large-snapshots\tjest\tstyle\t\t\tv0.4.3
no-large-snapshots\tvitest\tstyle\t\t\tv0.4.3
no-length-as-slice-end\tunicorn\trestriction\t\t🛠️\tv0.7.0
no-lifecycle-after-await\tvue\tcorrectness\t\t\tv1.39.0
no-lone-blocks\teslint\tstyle\t\t\tv0.15.6
no-lonely-if\teslint\tpedantic\t\t🚧\tv0.16.0
no-lonely-if\tunicorn\tpedantic\t\t🚧\tv0.0.18
no-loop-func\teslint\tpedantic\t\t\tv1.33.0
no-loss-of-precision\teslint\tcorrectness\t✅\t\tv0.0.7
no-magic-array-flat-depth\tunicorn\trestriction\t\t\tv0.4.2
no-magic-numbers\teslint\tstyle\t\t🚧\tv0.9.3
no-map-spread\toxc\tperf\t\t💡\tv0.11.0
no-meaningless-void-operator💭\ttypescript\tcorrectness\t✅\t🛠️ 💡\tv1.12.0
no-misleading-character-class\teslint\tcorrectness\t✅\t💡\tv1.17.0
no-misused-new\ttypescript\tcorrectness\t✅\t\tv0.0.7
no-misused-promises💭\ttypescript\tpedantic\t\t\tv1.11.0
no-misused-spread💭\ttypescript\tcorrectness\t✅\t💡\tv1.12.0
no-mixed-enums💭\ttypescript\tpedantic\t\t\tv1.12.0
no-mocks-import\tjest\tstyle\t\t\tv0.0.13
no-mocks-import\tvitest\tstyle\t\t\tv0.0.13
no-multi-assign\teslint\tstyle\t\t\tv0.15.4
no-multi-comp\treact\trestriction\t\t\tv1.43.0
no-multi-str\teslint\tstyle\t\t\tv0.5.3
no-multiple-resolved\tpromise\tsuspicious\t\t\tv1.19.0
no-multiple-slot-args\tvue\trestriction\t\t🚧\tv1.15.0
no-mutable-exports\timport\tstyle\t\t\tv0.15.13
no-named-as-default\timport\tsuspicious\t\t\tv0.2.3
no-named-as-default-member\timport\tsuspicious\t\t\tv0.2.1
no-named-default\timport\tstyle\t\t\tv0.15.3
no-named-export\timport\tstyle\t\t\tv1.19.0
no-namespace\timport\tstyle\t\t🚧\tv0.12.0
no-namespace\treact\tsuspicious\t\t\tv0.15.13
no-namespace\ttypescript\trestriction\t\t\tv0.0.8
no-negated-condition\teslint\tpedantic\t\t🚧\tv0.0.18
no-negated-condition\tunicorn\tpedantic\t\t🚧\tv0.0.18
no-negation-in-equality-check\tunicorn\tpedantic\t\t💡\tv0.5.3
no-nested-ternary\teslint\tstyle\t\t\tv0.15.4
no-nested-ternary\tunicorn\tstyle\t\t🛠️\tv0.0.18
no-nesting\tpromise\tstyle\t\t🚧\tv0.15.13
no-new\teslint\tsuspicious\t\t\tv0.4.0
no-new-array\tunicorn\tcorrectness\t✅\t⚠️ 💡\tv0.0.16
no-new-buffer\tunicorn\tpedantic\t\t💡\tv0.0.16
no-new-func\teslint\tstyle\t\t\tv0.9.2
no-new-native-nonconstructor\teslint\tcorrectness\t✅\t\tv0.3.3
no-new-require\tnode\trestriction\t\t\tv0.10.0
no-new-statics\tpromise\tcorrectness\t\t🛠️\tv0.6.1
no-new-wrappers\teslint\tpedantic\t\t🛠️\tv0.2.10
no-nodejs-modules\timport\tstyle\t\t\tv1.43.0
no-non-null-asserted-nullish-coalescing\ttypescript\trestriction\t\t💡\tv0.5.0
no-non-null-asserted-optional-chain\ttypescript\tcorrectness\t✅\t💡\tv0.0.6
no-non-null-assertion\ttypescript\trestriction\t\t🚧\tv0.5.0
no-noninteractive-element-interactions\tjsx-a11y\tcorrectness\t\t\tv1.65.0
no-noninteractive-element-to-interactive-role\tjsx-a11y\tcorrectness\t\t\tv1.64.0
no-noninteractive-tabindex\tjsx-a11y\tcorrectness\t\t\tv0.15.4
no-nonoctal-decimal-escape\teslint\tcorrectness\t✅\t💡\tv0.2.10
no-null\tunicorn\tstyle\t\t⚠️ 🛠️\tv0.0.21
no-obj-calls\teslint\tcorrectness\t✅\t\tv0.0.7
no-object-as-default-parameter\tunicorn\tpedantic\t\t\tv0.0.16
no-object-constructor\teslint\tpedantic\t\t🚧\tv0.13.2
no-object-type-as-default-prop\treact\tperf\t\t\tv1.66.0
no-optional-chaining\toxc\trestriction\t\t\tv0.5.0
no-page-custom-font\tnextjs\tcorrectness\t\t\tv0.3.3
no-param-reassign\teslint\trestriction\t\t\tv1.20.0
no-path-concat\tnode\trestriction\t\t\tv1.49.0
no-plusplus\teslint\trestriction\t\t💡\tv0.9.5
no-process-env\tnode\trestriction\t\t\tv1.23.0
no-process-exit\tunicorn\trestriction\t\t🚧\tv0.2.9
no-promise-executor-return\teslint\tpedantic\t\t🚧\tv1.33.0
no-promise-in-callback\tpromise\tsuspicious\t\t\tv0.13.1
no-proto\teslint\trestriction\t\t🚧\tv0.2.14
no-prototype-builtins\teslint\tpedantic\t\t🚧\tv0.0.5
no-react-children\treact\trestriction\t\t\tv1.53.0
no-redeclare\teslint\tpedantic\t\t\tv0.0.13
no-redundant-roles\tjsx-a11y\tcorrectness\t\t🛠️\tv0.2.1
no-redundant-should-component-update\treact\tstyle\t\t\tv1.33.0
no-redundant-type-constituents💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
no-regex-spaces\teslint\trestriction\t\t🛠️\tv0.0.18
no-relative-parent-imports\timport\trestriction\t\t\tv1.43.0
no-render-return-value\treact\tcorrectness\t\t\tv0.0.15
no-require-imports\ttypescript\trestriction\t\t🚧\tv0.13.0
no-required-prop-with-default\tvue\tsuspicious\t\t💡\tv1.17.0
no-reserved-component-names\tvue\tcorrectness\t\t\tv1.68.0
no-reserved-keys\tvue\tcorrectness\t\t\tvnext
no-reserved-props\tvue\tcorrectness\t\t\tvnext
no-rest-spread-properties\toxc\trestriction\t\t\tv0.4.2
no-restricted-exports\teslint\tnursery\t\t\tv1.59.0
no-restricted-globals\teslint\trestriction\t\t\tv0.4.0
no-restricted-imports\teslint\trestriction\t\t\tv0.15.0
no-restricted-jest-methods\tjest\tstyle\t\t\tv0.2.3
no-restricted-matchers\tjest\tstyle\t\t\tv0.2.3
no-restricted-matchers\tvitest\tstyle\t\t\tv0.2.3
no-restricted-properties\teslint\trestriction\t\t\tv1.63.0
no-restricted-types\ttypescript\trestriction\t\t🛠️ 💡\tv1.31.0
no-restricted-vi-methods\tvitest\tstyle\t\t\tv0.2.3
no-return-assign\teslint\tstyle\t\t\tv0.9.10
no-return-in-finally\tpromise\tnursery\t\t\tv0.7.1
no-return-wrap\tpromise\tstyle\t\t🚧\tv0.15.14
no-script-component-in-head\tnextjs\tcorrectness\t\t\tv0.2.0
no-script-url\teslint\tstyle\t\t\tv0.2.15
no-self-assign\teslint\tcorrectness\t✅\t\tv0.0.5
no-self-compare\teslint\tpedantic\t\t\tv0.0.3
no-self-import\timport\tsuspicious\t\t\tv0.0.13
no-sequences\teslint\trestriction\t\t\tv1.33.0
no-set-state\treact\tstyle\t\t\tv0.5.2
no-setter-return\teslint\tcorrectness\t✅\t\tv0.0.3
no-shadow\teslint\tsuspicious\t\t\tv1.48.0
no-shadow-restricted-names\teslint\tcorrectness\t✅\t\tv0.0.3
no-shared-component-data\tvue\tcorrectness\t\t🚧\tv1.67.0
no-single-promise-in-promise-methods\tunicorn\tcorrectness\t✅\t🛠️\tv0.2.18
no-sparse-arrays\teslint\tcorrectness\t✅\t\tv0.0.4
no-standalone-expect\tjest\tcorrectness\t\t\tv0.0.13
no-standalone-expect\tvitest\tcorrectness\t\t\tv0.0.13
no-static-element-interactions\tjsx-a11y\tcorrectness\t\t\tv1.37.0
no-static-only-class\tunicorn\tpedantic\t\t⚠️ 🛠️\tv0.0.16
no-string-refs\treact\tcorrectness\t\t\tv0.0.15
no-styled-jsx-in-document\tnextjs\tcorrectness\t\t\tv0.3.3
no-sync-scripts\tnextjs\tcorrectness\t\t\tv0.2.0
no-template-curly-in-string\teslint\tstyle\t\t\tv0.2.14
no-ternary\teslint\tstyle\t\t\tv0.2.14
no-test-prefixes\tjest\tstyle\t\t🛠️\tv0.0.7
no-test-prefixes\tvitest\tstyle\t\t🛠️\tv0.0.7
no-test-return-statement\tjest\tstyle\t\t\tv0.2.0
no-test-return-statement\tvitest\tstyle\t\t\tv0.2.0
no-thenable\tunicorn\tcorrectness\t✅\t\tv0.0.13
no-this-alias\ttypescript\tcorrectness\t✅\t\tv0.0.7
no-this-assignment\tunicorn\tpedantic\t\t\tv0.0.18
no-this-before-super\teslint\tcorrectness\t✅\t\tv0.2.6
no-this-in-before-route-enter\tvue\tcorrectness\t\t\tv1.37.0
no-this-in-exported-function\toxc\tsuspicious\t\t\tv1.33.0
no-this-in-sfc\treact\tcorrectness\t\t\tv1.37.0
no-throw-literal\teslint\tpedantic\t\t💡\tv0.9.10
no-title-in-document-head\tnextjs\tcorrectness\t\t\tv0.2.0
no-typeof-undefined\tunicorn\tpedantic\t\t🛠️ 💡\tv0.0.18
no-typos\tnextjs\tcorrectness\t\t🚧\tv0.2.1
no-unassigned-import\timport\tsuspicious\t\t\tv0.16.11
no-unassigned-vars\teslint\tcorrectness\t✅\t\tv1.10.0
no-undef\teslint\tnursery\t\t\tv0.0.8
no-undefined\teslint\trestriction\t\t\tv0.5.3
no-underscore-dangle\teslint\tsuspicious\t\t\tv1.62.0
no-unescaped-entities\treact\tpedantic\t\t🚧\tv0.0.15
no-unexpected-multiline\teslint\tsuspicious\t\t⚠️ 🛠️\tv0.9.7
no-unknown-property\treact\trestriction\t\t🚧\tv0.2.0
no-unmodified-loop-condition\teslint\tsuspicious\t\t\tv1.48.0
no-unnecessary-array-flat-depth\tunicorn\tpedantic\t\t💡\tv0.16.12
no-unnecessary-array-splice-count\tunicorn\tpedantic\t\t🛠️\tv1.20.0
no-unnecessary-await\tunicorn\tcorrectness\t✅\t🛠️\tv0.0.12
no-unnecessary-boolean-literal-compare💭\ttypescript\tsuspicious\t\t🚧\tv1.12.0
no-unnecessary-condition💭\ttypescript\tnursery\t\t\tv1.48.0
no-unnecessary-parameter-property-assignment\ttypescript\tcorrectness\t✅\t💡\tv0.15.13
no-unnecessary-qualifier💭\ttypescript\tstyle\t\t\tv1.49.0
no-unnecessary-slice-end\tunicorn\tpedantic\t\t🛠️\tv0.16.10
no-unnecessary-template-expression💭\ttypescript\tsuspicious\t\t🛠️\tv1.12.0
no-unnecessary-type-arguments💭\ttypescript\tsuspicious\t\t🛠️\tv1.12.0
no-unnecessary-type-assertion💭\ttypescript\tsuspicious\t\t🛠️\tv1.12.0
no-unnecessary-type-constraint\ttypescript\tsuspicious\t\t🚧\tv0.0.6
no-unnecessary-type-conversion💭\ttypescript\tsuspicious\t\t\tv1.49.0
no-unnecessary-type-parameters💭\ttypescript\tsuspicious\t\t\tv1.49.0
no-unneeded-async-expect-function\tjest\tstyle\t\t🛠️\tv1.39.0
no-unneeded-async-expect-function\tvitest\tstyle\t\t🛠️\tv1.39.0
no-unneeded-ternary\teslint\tsuspicious\t\t⚠️ 🛠️\tv0.15.12
no-unreachable\teslint\tcorrectness\t✅\t\tv0.4.4
no-unreadable-array-destructuring\tunicorn\tstyle\t\t🚧\tv0.0.19
no-unreadable-iife\tunicorn\tpedantic\t\t\tv0.0.19
no-unsafe\treact\tcorrectness\t\t\tv1.35.0
no-unsafe-argument💭\ttypescript\tpedantic\t\t\tv1.12.0
no-unsafe-assignment💭\ttypescript\tpedantic\t\t\tv1.12.0
no-unsafe-call💭\ttypescript\tpedantic\t\t\tv1.12.0
no-unsafe-declaration-merging\ttypescript\tcorrectness\t✅\t\tv0.0.11
no-unsafe-enum-comparison💭\ttypescript\tsuspicious\t\t💡\tv1.12.0
no-unsafe-finally\teslint\tcorrectness\t✅\t\tv0.0.5
no-unsafe-function-type\ttypescript\tpedantic\t\t\tv0.11.1
no-unsafe-member-access💭\ttypescript\tpedantic\t\t\tv1.12.0
no-unsafe-negation\teslint\tcorrectness\t✅\t🛠️\tv0.0.3
no-unsafe-optional-chaining\teslint\tcorrectness\t✅\t\tv0.0.5
no-unsafe-return💭\ttypescript\tpedantic\t\t\tv1.12.0
no-unsafe-type-assertion💭\ttypescript\tsuspicious\t\t\tv1.12.0
no-unsafe-unary-minus💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
no-unstable-nested-components\treact\tsuspicious\t\t\tv1.66.0
no-untyped-mock-factory\tjest\tstyle\t\t🛠️\tv0.2.15
no-unused-expressions\teslint\tcorrectness\t✅\t\tv0.14.0
no-unused-labels\teslint\tcorrectness\t✅\t🛠️\tv0.0.3
no-unused-private-class-members\teslint\tcorrectness\t✅\t\tv0.1.1
no-unused-vars\teslint\tcorrectness\t✅\t⚠️ 🛠 💡\tv0.7.0
no-unwanted-polyfillio\tnextjs\tcorrectness\t\t\tv0.2.7
no-use-before-define\teslint\trestriction\t\t\tv1.49.0
no-useless-assignment\teslint\tnursery\t\t\tv1.59.0
no-useless-backreference\teslint\tcorrectness\t✅\t\tv0.16.10
no-useless-call\teslint\tperf\t\t\tv0.15.9
no-useless-catch\teslint\tcorrectness\t✅\t\tv0.0.5
no-useless-collection-argument\tunicorn\tstyle\t\t💡\tv1.28.0
no-useless-computed-key\teslint\tstyle\t\t🛠️\tv1.16.0
no-useless-concat\teslint\tsuspicious\t\t🚧\tv0.4.2
no-useless-constructor\teslint\tsuspicious\t\t💡\tv0.4.4
no-useless-default-assignment💭\ttypescript\tcorrectness\t✅\t\tv1.49.0
no-useless-empty-export\ttypescript\tcorrectness\t✅\t🛠️\tv0.4.4
no-useless-error-capture-stack-trace\tunicorn\trestriction\t\t💡\tv1.20.0
no-useless-escape\teslint\tcorrectness\t✅\t🛠️\tv0.0.5
no-useless-fallback-in-spread\tunicorn\tcorrectness\t✅\t🛠️\tv0.0.16
no-useless-iterator-to-array\tunicorn\tnursery\t\t🛠️ 💡\tv1.59.0
no-useless-length-check\tunicorn\tcorrectness\t✅\t🚧\tv0.0.19
no-useless-promise-resolve-reject\tunicorn\tpedantic\t\t🛠️\tv0.0.18
no-useless-rename\teslint\tcorrectness\t✅\t🛠️\tv0.2.14
no-useless-return\teslint\tpedantic\t\t🚧\tv1.32.0
no-useless-spread\tunicorn\tcorrectness\t✅\t⚠️ 🛠️\tv0.0.19
no-useless-switch-case\tunicorn\tpedantic\t\t🚧\tv0.0.18
no-useless-undefined\tunicorn\tpedantic\t\t🛠️\tv0.6.1
no-var\teslint\trestriction\t\t🛠️\tv0.1.1
no-var-requires\ttypescript\trestriction\t\t\tv0.0.7
no-void\teslint\trestriction\t\t💡\tv0.2.5
no-warning-comments\teslint\tpedantic\t\t\tv1.24.0
no-watch-after-await\tvue\tcorrectness\t\t\tv1.67.0
no-webpack-loader-syntax\timport\trestriction\t\t\tv0.7.0
no-will-update-set-state\treact\tcorrectness\t\t\tv1.37.0
no-with\teslint\tcorrectness\t✅\t\tv0.2.14
no-wrapper-object-types\ttypescript\tcorrectness\t✅\t🛠️\tv0.8.0
no-zero-fractions\tunicorn\tstyle\t\t🛠️\tv0.0.18
non-nullable-type-assertion-style💭\ttypescript\trestriction\t\t💡\tv1.12.0
number-arg-out-of-range\toxc\tcorrectness\t✅\t\tv0.0.3
number-literal-case\tunicorn\tstyle\t\t🛠️\tv0.0.18
numeric-separators-style\tunicorn\tstyle\t\t🛠️\tv0.0.19
object-shorthand\teslint\tstyle\t\t🛠️\tv1.59.0
only-export-components\treact\trestriction\t\t\tv1.23.0
only-throw-error💭\ttypescript\tpedantic\t\t\tv1.12.0
only-used-in-recursion\toxc\tcorrectness\t✅\t⚠️ 🛠️\tv0.1.1
operator-assignment\teslint\tstyle\t\t⚠️ 🛠️\tv0.15.13
padding-around-after-all-blocks\tjest\tstyle\t\t🛠️\tv1.59.0
padding-around-after-all-blocks\tvitest\tstyle\t\t🛠️\tv1.66.0
padding-around-test-blocks\tjest\tstyle\t\t🛠️\tv1.13.0
param-names\tpromise\tstyle\t\t\tv0.6.1
parameter-properties\ttypescript\tstyle\t\t\tv1.48.0
prefer-add-event-listener\tunicorn\tsuspicious\t\t🚧\tv0.0.16
prefer-array-find\tunicorn\tperf\t\t🚧\tv0.16.12
prefer-array-flat\tunicorn\tpedantic\t\t⚠️ 🛠️\tv0.0.20
prefer-array-flat-map\tunicorn\tperf\t\t🛠️\tv0.0.14
prefer-array-index-of\tunicorn\tstyle\t\t🚧\tv0.16.12
prefer-array-some\tunicorn\tpedantic\t\t💡\tv0.0.18
prefer-arrow-callback\teslint\tstyle\t\t🛠️\tv1.65.0
prefer-as-const\ttypescript\tcorrectness\t✅\t🛠️\tv0.0.8
prefer-at\tunicorn\tpedantic\t\t⚠️ 🛠️\tv1.20.0
prefer-await-to-callbacks\tpromise\tstyle\t\t\tv0.9.10
prefer-await-to-then\tpromise\tstyle\t\t\tv0.7.1
prefer-bigint-literals\tunicorn\tstyle\t\t🛠️\tv1.30.0
prefer-blob-reading-methods\tunicorn\tpedantic\t\t🚧\tv0.0.16
prefer-called-exactly-once-with\tvitest\tstyle\t\t⚠️ 🛠️\tv1.58.0
prefer-called-once\tvitest\tstyle\t\t🛠️\tv1.39.0
prefer-called-times\tvitest\tstyle\t\t🛠️\tv1.35.0
prefer-called-with\tjest\tstyle\t\t🛠️\tv0.2.5
prefer-called-with\tvitest\tstyle\t\t🛠️\tv0.2.5
prefer-catch\tpromise\tstyle\t\t🚧\tv0.15.14
prefer-class-fields\tunicorn\tstyle\t\t🛠️ 💡\tv1.20.0
prefer-classlist-toggle\tunicorn\tstyle\t\t🛠️\tv1.20.0
prefer-code-point\tunicorn\tpedantic\t\t🛠️\tv0.0.16
prefer-comparison-matcher\tjest\tstyle\t\t🛠️\tv0.2.15
prefer-comparison-matcher\tvitest\tstyle\t\t🛠️\tv0.2.15
prefer-const\teslint\tstyle\t\t🛠️\tv1.43.0
prefer-date-now\tunicorn\tpedantic\t\t🛠️\tv0.0.16
prefer-default-export\timport\tstyle\t\t\tv1.4.0
prefer-default-parameters\tunicorn\tstyle\t\t🛠️\tv1.33.0
prefer-describe-function-title\tvitest\tstyle\t\t🛠️\tv1.39.0
prefer-destructuring\teslint\tstyle\t\t🛠️\tv1.10.0
prefer-dom-node-append\tunicorn\tpedantic\t\t🛠️\tv0.0.18
prefer-dom-node-dataset\tunicorn\tpedantic\t\t🛠️\tv0.0.18
prefer-dom-node-remove\tunicorn\tpedantic\t\t🚧\tv0.0.18
prefer-dom-node-text-content\tunicorn\tstyle\t\t🛠️\tv0.0.21
prefer-each\tjest\tstyle\t\t\tv0.9.0
prefer-each\tvitest\tstyle\t\t\tv0.9.0
prefer-ending-with-an-expect\tjest\tstyle\t\t\tv1.60.0
prefer-enum-initializers\ttypescript\tpedantic\t\t💡\tv0.3.2
prefer-equality-matcher\tjest\tstyle\t\t💡\tv0.2.9
prefer-equality-matcher\tvitest\tstyle\t\t💡\tv0.2.9
prefer-es6-class\treact\tstyle\t\t\tv0.5.0
prefer-event-target\tunicorn\tpedantic\t\t\tv0.0.18
prefer-expect-assertions\tjest\tstyle\t\t💡\tv1.62.0
prefer-expect-assertions\tvitest\tstyle\t\t💡\tv1.62.0
prefer-expect-resolves\tjest\tstyle\t\t🛠️\tv0.2.14
prefer-expect-resolves\tvitest\tstyle\t\t🛠️\tv0.2.14
prefer-expect-type-of\tvitest\tstyle\t\t🛠️\tv1.44.0
prefer-exponentiation-operator\teslint\tstyle\t\t🛠️\tv0.4.0
prefer-find💭\ttypescript\tstyle\t\t\tv1.49.0
prefer-for-of\ttypescript\tstyle\t\t🚧\tv0.2.16
prefer-function-component\treact\trestriction\t\t\tv1.59.0
prefer-function-type\ttypescript\tstyle\t\t🛠️\tv0.2.11
prefer-global-this\tunicorn\tstyle\t\t💡\tv0.16.12
prefer-hooks-in-order\tjest\tstyle\t\t\tv0.6.0
prefer-hooks-in-order\tvitest\tstyle\t\t\tv0.6.0
prefer-hooks-on-top\tjest\tstyle\t\t\tv0.4.2
prefer-hooks-on-top\tvitest\tstyle\t\t\tv0.4.2
prefer-import-from-vue\tvue\tcorrectness\t\t🛠️\tv1.20.0
prefer-import-in-mock\tvitest\tstyle\t\t🛠️\tv1.49.0
prefer-import-meta-properties\tunicorn\tpedantic\t\t🛠️\tv1.59.0
prefer-importing-jest-globals\tjest\tstyle\t\t🛠️\tv1.60.0
prefer-importing-vitest-globals\tvitest\tstyle\t\t🛠️\tv1.59.0
prefer-includes💭\ttypescript\tpedantic\t\t🛠️\tv1.29.0
prefer-includes\tunicorn\tstyle\t\t💡\tv0.0.18
prefer-jest-mocked\tjest\tstyle\t\t🛠️\tv0.5.0
prefer-keyboard-event-key\tunicorn\tstyle\t\t🛠️\tv1.33.0
prefer-literal-enum-member\ttypescript\trestriction\t\t\tv0.3.2
prefer-logical-operator-over-ternary\tunicorn\tstyle\t\t💡\tv0.0.15
prefer-lowercase-title\tjest\tstyle\t\t🛠️\tv0.15.9
prefer-lowercase-title\tvitest\tstyle\t\t🛠️\tv0.15.9
prefer-math-min-max\tunicorn\tpedantic\t\t🛠️\tv0.10.1
prefer-math-trunc\tunicorn\tpedantic\t\t💡\tv0.0.18
prefer-mock-promise-shorthand\tjest\tstyle\t\t🛠️\tv0.2.16
prefer-mock-promise-shorthand\tvitest\tstyle\t\t🛠️\tv0.2.16
prefer-mock-return-shorthand\tjest\tstyle\t\t🛠️\tv1.49.0
prefer-mock-return-shorthand\tvitest\tstyle\t\t🛠️\tv1.49.0
prefer-modern-dom-apis\tunicorn\tstyle\t\t💡\tv0.0.20
prefer-modern-math-apis\tunicorn\trestriction\t\t🚧\tv0.1.1
prefer-module\tunicorn\trestriction\t\t🚧\tv1.50.0
prefer-named-capture-group\teslint\tstyle\t\t\tv1.68.0
prefer-namespace-keyword\ttypescript\tcorrectness\t✅\t🛠️\tv0.7.0
prefer-native-coercion-functions\tunicorn\tpedantic\t\t🚧\tv0.0.19
prefer-negative-index\tunicorn\tstyle\t\t🛠️\tv0.13.2
prefer-node-protocol\tunicorn\trestriction\t\t🛠️\tv0.0.19
prefer-nullish-coalescing💭\ttypescript\tpedantic\t\t🛠️\tv1.33.0
prefer-number-properties\tunicorn\trestriction\t\t⚠️ 🛠️\tv0.0.19
prefer-numeric-literals\teslint\tstyle\t\t🛠️\tv0.7.0
prefer-object-from-entries\tunicorn\tstyle\t\t🚧\tv0.16.12
prefer-object-has-own\teslint\tstyle\t\t🛠️\tv0.11.0
prefer-object-spread\teslint\tstyle\t\t🛠️\tv0.15.9
prefer-optional-catch-binding\tunicorn\tstyle\t\t🛠️\tv0.0.17
prefer-optional-chain💭\ttypescript\tnursery\t\t⚠️ 🛠 💡\tv1.39.0
prefer-promise-reject-errors\teslint\tstyle\t\t\tv0.15.7
prefer-promise-reject-errors💭\ttypescript\tpedantic\t\t\tv1.12.0
prefer-prototype-methods\tunicorn\tpedantic\t\t🛠️\tv0.0.21
prefer-query-selector\tunicorn\tpedantic\t\t🛠️\tv0.0.15
prefer-readonly💭\ttypescript\tstyle\t\t\tv0.0.8
prefer-readonly-parameter-types💭\ttypescript\tpedantic\t\t\tv1.49.0
prefer-reduce-type-parameter💭\ttypescript\tstyle\t\t🛠️\tv1.12.0
prefer-reflect-apply\tunicorn\tstyle\t\t💡\tv0.0.19
prefer-regex-literals\teslint\tstyle\t\t🚧\tv1.64.0
prefer-regexp-exec💭\ttypescript\tstyle\t\t\tv1.49.0
prefer-regexp-test\tunicorn\tpedantic\t\t🛠️\tv0.0.16
prefer-response-static-json\tunicorn\tstyle\t\t💡\tv1.29.0
prefer-rest-params\teslint\tstyle\t\t\tv0.15.4
prefer-return-this-type💭\ttypescript\tstyle\t\t🛠️\tv1.12.0
prefer-set-has\tunicorn\tperf\t\t⚠️ 🛠️\tv0.13.2
prefer-set-size\tunicorn\tcorrectness\t✅\t🛠️\tv0.0.19
prefer-snapshot-hint\tjest\tcorrectness\t\t\tv1.59.0
prefer-snapshot-hint\tvitest\tcorrectness\t\t\tv1.59.0
prefer-spread\teslint\tstyle\t\t\tv0.0.17
prefer-spread\tunicorn\tstyle\t\t🛠️\tv0.0.17
prefer-spy-on\tjest\tstyle\t\t💡\tv0.2.14
prefer-spy-on\tvitest\tstyle\t\t💡\tv0.2.14
prefer-strict-boolean-matchers\tvitest\tstyle\t\t🛠️\tv1.57.0
prefer-strict-equal\tjest\tstyle\t\t🛠️\tv0.2.13
prefer-strict-equal\tvitest\tstyle\t\t🛠️\tv0.2.13
prefer-string-raw\tunicorn\tstyle\t\t🛠️\tv0.12.0
prefer-string-replace-all\tunicorn\tpedantic\t\t🛠️\tv0.0.18
prefer-string-slice\tunicorn\tpedantic\t\t🛠️\tv0.0.18
prefer-string-starts-ends-with💭\ttypescript\tstyle\t✅\t\tv0.0.8
prefer-string-starts-ends-with\tunicorn\tcorrectness\t✅\t🛠️\tv0.0.18
prefer-string-trim-start-end\tunicorn\tstyle\t\t🛠️\tv0.0.16
prefer-structured-clone\tunicorn\tstyle\t\t💡\tv0.9.0
prefer-tag-over-role\tjsx-a11y\tcorrectness\t\t\tv0.1.1
prefer-template\teslint\tstyle\t\t🛠️\tv1.12.0
prefer-ternary\tunicorn\tstyle\t\t🚧\tv1.50.0
prefer-to-be\tjest\tstyle\t\t🛠️\tv0.2.14
prefer-to-be\tvitest\tstyle\t\t🛠️\tv0.2.14
prefer-to-be-falsy\tvitest\tstyle\t\t🛠️\tv0.7.1
prefer-to-be-object\tvitest\tstyle\t\t🛠️\tv0.9.2
prefer-to-be-truthy\tvitest\tstyle\t\t🛠️\tv0.7.1
prefer-to-contain\tjest\tstyle\t\t🛠️\tv0.2.14
prefer-to-contain\tvitest\tstyle\t\t🛠️\tv0.2.14
prefer-to-have-been-called\tjest\tstyle\t\t🛠️\tv1.34.0
prefer-to-have-been-called-times\tjest\tstyle\t\t🛠️\tv1.34.0
prefer-to-have-been-called-times\tvitest\tstyle\t\t🛠️\tv1.34.0
prefer-to-have-length\tjest\tstyle\t\t🛠️\tv0.2.13
prefer-to-have-length\tvitest\tstyle\t\t🛠️\tv0.2.13
prefer-todo\tjest\tstyle\t\t🛠️\tv0.0.16
prefer-todo\tvitest\tstyle\t\t🛠️\tv0.0.16
prefer-top-level-await\tunicorn\tpedantic\t\t🚧\tv1.20.0
prefer-ts-expect-error\ttypescript\tpedantic\t\t🛠️\tv0.2.11
prefer-type-error\tunicorn\tpedantic\t\t🛠️\tv0.0.16
preserve-caught-error\teslint\tsuspicious\t\t🛠️\tv1.16.0
promise-function-async💭\ttypescript\trestriction\t\t🛠️\tv1.12.0
prop-name-casing\tvue\tstyle\t\t\tvnext
radix\teslint\tpedantic\t\t⚠️ 🛠️\tv0.3.3
react-in-jsx-scope\treact\tsuspicious\t\t\tv0.0.20
related-getter-setter-pairs💭\ttypescript\tpedantic\t\t\tv1.12.0
relative-url-style\tunicorn\tstyle\t\t🛠️ 💡\tv1.44.0
require-array-join-separator\tunicorn\tstyle\t\t🛠️\tv0.0.19
require-array-sort-compare💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
require-await\teslint\tpedantic\t\t⚠️ 🛠️\tv0.4.2
require-await💭\ttypescript\tpedantic\t\t💡\tv1.12.0
require-awaited-expect-poll\tvitest\tcorrectness\t\t\tv1.58.0
require-default-export\tvue\tsuspicious\t\t\tv1.21.0
require-direct-export\tvue\tstyle\t\t\tvnext
require-hook\tjest\tstyle\t\t\tv0.3.2
require-hook\tvitest\tstyle\t\t\tv0.3.2
require-local-test-context-for-concurrent-snapshots\tvitest\tcorrectness\t\t\tv0.8.0
require-mock-type-parameters\tvitest\tcorrectness\t\t\tv1.58.0
require-module-attributes\tunicorn\tstyle\t\t💡\tv1.35.0
require-module-specifiers\tunicorn\tsuspicious\t\t🛠️\tv1.20.0
require-number-to-fixed-digits-argument\tunicorn\tpedantic\t\t🛠️\tv0.0.15
require-param\tjsdoc\tpedantic\t\t🚧\tv0.4.3
require-param-description\tjsdoc\tpedantic\t\t🚧\tv0.4.4
require-param-name\tjsdoc\tpedantic\t\t\tv0.4.3
require-param-type\tjsdoc\tpedantic\t\t🚧\tv0.4.4
require-post-message-target-origin\tunicorn\tsuspicious\t\t💡\tv0.15.15
require-prop-type-constructor\tvue\tcorrectness\t\t🛠️\tv1.68.0
require-prop-types\tvue\tstyle\t\t\tvnext
require-property\tjsdoc\tcorrectness\t\t🚧\tv0.2.18
require-property-description\tjsdoc\tcorrectness\t\t\tv0.2.18
require-property-name\tjsdoc\tcorrectness\t\t\tv0.2.18
require-property-type\tjsdoc\tcorrectness\t\t\tv0.2.18
require-render-return\treact\tnursery\t\t\tv0.2.0
require-render-return\tvue\tcorrectness\t\t\tv1.67.0
require-returns\tjsdoc\tpedantic\t\t🚧\tv0.4.0
require-returns-description\tjsdoc\tpedantic\t\t\tv0.4.0
require-returns-type\tjsdoc\tpedantic\t\t\tv0.4.3
require-slots-as-functions\tvue\tcorrectness\t\t\tv1.67.0
require-test-timeout\tvitest\trestriction\t\t\tv1.58.0
require-throws-description\tjsdoc\tstyle\t\t\tv1.65.0
require-throws-type\tjsdoc\tpedantic\t\t\tv1.65.0
require-to-throw-message\tjest\tcorrectness\t\t\tv0.2.9
require-to-throw-message\tvitest\tcorrectness\t\t\tv0.2.9
require-top-level-describe\tjest\tstyle\t\t\tv0.4.2
require-top-level-describe\tvitest\tstyle\t\t\tv0.4.2
require-typed-ref\tvue\tstyle\t\t\tv1.17.0
require-unicode-regexp\teslint\tpedantic\t\t🚧\tv1.63.0
require-yield\teslint\tcorrectness\t✅\t\tv0.0.4
require-yields\tjsdoc\tcorrectness\t\t\tv0.3.2
require-yields-description\tjsdoc\tstyle\t\t\tv1.68.0
require-yields-type\tjsdoc\tpedantic\t\t\tv1.65.0
restrict-plus-operands💭\ttypescript\tpedantic\t\t\tv1.12.0
restrict-template-expressions💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
return-await💭\ttypescript\tpedantic\t\t🛠️ 💡\tv1.12.0
return-in-computed-property\tvue\tcorrectness\t\t\tv1.63.0
return-in-emits-validator\tvue\tcorrectness\t\t\tv1.67.0
role-has-required-aria-props\tjsx-a11y\tcorrectness\t\t\tv0.2.0
role-supports-aria-props\tjsx-a11y\tcorrectness\t\t\tv0.2.0
rules-of-hooks\treact\tpedantic\t\t\tv0.3.3
scope\tjsx-a11y\tcorrectness\t\t🛠️\tv0.0.19
self-closing-comp\treact\tstyle\t\t🛠️\tv0.9.3
sort-imports\teslint\tstyle\t\t🛠️\tv0.4.4
sort-keys\teslint\tstyle\t\t🛠️\tv0.9.4
sort-vars\teslint\tpedantic\t\t🚧\tv0.9.3
spec-only\tpromise\trestriction\t\t\tv0.9.2
state-in-constructor\treact\tstyle\t\t\tv1.26.0
strict-boolean-expressions💭\ttypescript\tpedantic\t\t🚧\tv1.25.0
strict-void-return💭\ttypescript\tpedantic\t\t\tv0.0.8
style-prop-object\treact\tsuspicious\t\t\tv0.11.0
switch-case-braces\tunicorn\tstyle\t\t🛠️\tv0.0.15
switch-case-break-position\tunicorn\tstyle\t\t🚧\tv1.59.0
switch-exhaustiveness-check💭\ttypescript\tpedantic\t\t💡\tv1.12.0
symbol-description\teslint\tpedantic\t\t\tv0.4.0
tabindex-no-positive\tjsx-a11y\tcorrectness\t\t⚠️ 💡\tv0.0.21
text-encoding-identifier-case\tunicorn\tstyle\t\t🛠️\tv0.0.15
throw-new-error\tunicorn\tstyle\t\t🛠️\tv0.0.14
triple-slash-reference\ttypescript\tcorrectness\t✅\t\tv0.2.0
unambiguous\timport\trestriction\t\t\tv0.11.1
unbound-method💭\ttypescript\tcorrectness\t✅\t\tv1.12.0
unicode-bom\teslint\trestriction\t\t🛠️\tv0.3.3
unified-signatures\ttypescript\tstyle\t\t\tv1.48.0
uninvoked-array-callback\toxc\tcorrectness\t✅\t\tv0.0.3
use-isnan\teslint\tcorrectness\t✅\t🛠️\tv0.0.3
use-unknown-in-catch-callback-variable💭\ttypescript\trestriction\t\t💡\tv1.12.0
valid-define-emits\tvue\tcorrectness\t\t🚧\tv1.14.0
valid-define-options\tvue\tcorrectness\t\t\tv1.67.0
valid-define-props\tvue\tcorrectness\t\t🚧\tv1.15.0
valid-describe-callback\tjest\tcorrectness\t\t\tv0.0.8
valid-describe-callback\tvitest\tcorrectness\t\t\tv0.0.8
valid-expect\tjest\tcorrectness\t\t💡\tv0.0.14
valid-expect\tvitest\tcorrectness\t\t💡\tv0.0.14
valid-expect-in-promise\tjest\tcorrectness\t\t\tv1.60.0
valid-expect-in-promise\tvitest\tcorrectness\t\t\tv1.60.0
valid-next-tick\tvue\tcorrectness\t\t🛠️\tv1.67.0
valid-params\tpromise\tcorrectness\t\t\tv0.7.1
valid-title\tjest\tcorrectness\t\t🛠️\tv0.0.14
valid-title\tvitest\tcorrectness\t\t🛠️\tv0.0.14
valid-typeof\teslint\tcorrectness\t✅\t🛠️\tv0.0.3
vars-on-top\teslint\tstyle\t\t\tv0.15.4
void-dom-elements-no-children\treact\tcorrectness\t\t\tv0.2.11
warn-todo\tvitest\tcorrectness\t\t\tv1.37.0
yoda\teslint\tstyle\t\t🛠️\tv0.14.1
`

export function oxlintOfficialRuleset(): Set<string> {
	return new Set(
		RAW_OXLINT_RULE_TABLE.trim()
			.split("\n")
			.filter((line) => line.trim() !== "")
			.map((line) => line.split("\t"))
			.map(([cell1, cell2]) => `${cell2}/${cell1}`)
			.map(normaliseOxlintRule)
			.filter(isAcceptedOxlintRule),
	)
}
