name: Yarn zero-install cache
description: Enables Yarn via Corepack in Node.js and restores dependencies from the Yarn zero-install cache.
author: Steffen Diswal

inputs:
  registry-url:
    description: Supplied to `actions/setup-node`.
    required: false

runs:
  using: composite
  steps:
    - name: Enable Yarn via Corepack # https://github.com/actions/setup-node/issues/899#issuecomment-1823139737 and https://github.com/actions/setup-node/issues/531
      run: corepack enable yarn
      shell: bash
    - name: Install Node.js and npm
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # https://github.com/actions/setup-node/releases/tag/v4.0.1 (pinned to the commit SHA)
      with:
        node-version: 20
        registry-url: ${{ inputs.registry-url }}
    - name: Restore unplugged dependencies from the workflow cache
      id: cache-yarn-unplugged
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # https://github.com/actions/cache/releases/tag/v3.3.2 (pinned to the commit SHA)
      with:
        path: ./.yarn/unplugged/
        key: ${{ runner.os }}-yarn-unplugged-dependencies-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-unplugged-dependencies-
    - name: Make dependencies executable from package scripts
      if: steps.cache-yarn-unplugged.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
    - name: Ensure that dependencies have been deduplicated
      if: steps.cache-yarn-unplugged.outputs.cache-hit != 'true'
      run: yarn dedupe --check
      shell: bash
