= Generic JSX Preset for ESLint
:experimental:
:source-highlighter: highlight.js

This package provides a predefined, opinionated https://eslint.org[ESLint] configuration intended to be used as a foundation for any web project that uses the JSX syntax for components such as https://qwik.builder.io[Qwik].

[CAUTION]
====
* For a Next.js app, use https://github.com/rainstormy/presets-web/tree/main/packages/preset-eslint-next[@rainstormy/preset-eslint-next] instead.
* For Preact components, use https://github.com/rainstormy/presets-web/tree/main/packages/preset-eslint-preact[@rainstormy/preset-eslint-preact] instead.
* For React components, use https://github.com/rainstormy/presets-web/tree/main/packages/preset-eslint-react[@rainstormy/preset-eslint-react] instead.
* For Solid components, use https://github.com/rainstormy/presets-web/tree/main/packages/preset-eslint-solid[@rainstormy/preset-eslint-solid] instead.
====

This preset configures a subset of rules from the following plugins, which are installed along with the preset package:

* https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules[eslint-plugin-jsx-a11y] (with rule names prefixed by `jsx-a11y/`)
* https://github.com/jsx-eslint/eslint-plugin-react#list-of-supported-rules[eslint-plugin-react] (only for generic JSX rules, with rule names prefixed by `react/`)

== Installation
Install the `@rainstormy/preset-eslint-jsx` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/preset-eslint-jsx @rainstormy/preset-eslint-base eslint typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/preset-eslint-jsx @rainstormy/preset-eslint-base eslint typescript
----

[source,shell]
----
yarn add --dev @rainstormy/preset-eslint-jsx @rainstormy/preset-eslint-base eslint typescript
----

== Usage
Create or extend a https://eslint.org/docs/latest/use/configure/configuration-files-new[flat ESLint configuration file] (`eslint.config.js`) and apply the `eslintPresetJsx` preset.

For example (with the default options in comments):

[source,javascript]
----
import { eslintPresets } from "@rainstormy/preset-eslint-base"
import { eslintPresetJsx } from "@rainstormy/preset-eslint-jsx"

export default eslintPresets({
	additionalPresets: [
		// ...other presets...
		eslintPresetJsx({
			// targetFilePatterns: ["**/*.@(jsx|tsx)"],
		}),
	],
})
----

=== In Combination with Qwik
Install `eslint-plugin-qwik` and use the spread syntax (`...`) to add a custom configuration object after the preset configuration object.

For example:

[source,javascript]
----
import {
	eslintPresetAmbientTypeScriptModules,
	eslintPresets,
} from "@rainstormy/preset-eslint-base"
import { eslintPresetJsx } from "@rainstormy/preset-eslint-jsx"
import qwikPlugin from "eslint-plugin-qwik"

export default [
	...eslintPresets({
		additionalPresets: [
			eslintPresetAmbientTypeScriptModules(),
			eslintPresetJsx(),
		],
	}),
	{
		files: ["**/*.@(jsx|tsx)"],
		plugins: {
			qwik: qwikPlugin,
		},
		rules: {
			"react/function-component-definition": "off",
			"react/jsx-key": "off",
			"react/jsx-no-script-url": "off",
			"qwik/jsx-img": "error",
			"qwik/jsx-key": "error",
			"qwik/jsx-no-script-url": "error",
			"qwik/loader-location": "error",
			"qwik/no-react-props": "error",
			"qwik/prefer-classlist": "error",
			"qwik/unused-server": "error",
			"qwik/use-method-usage": "error",
			"qwik/valid-lexical-scope": "error",
		},
	},
]
----
