import { type EslintPluginRuleset } from "@rainstormy/presets-eslint/dist/EslintConfig.js"

export type EslintPluginNextRuleset = EslintPluginRuleset<
	"next",
	| "next/google-font-display"
	| "next/google-font-preconnect"
	| "next/inline-script-id"
	| "next/next-script-for-ga"
	| "next/no-assign-module-variable"
	| "next/no-async-client-component"
	| "next/no-before-interactive-script-outside-document"
	| "next/no-css-tags"
	| "next/no-document-import-in-page"
	| "next/no-duplicate-head"
	| "next/no-head-element"
	| "next/no-head-import-in-document"
	| "next/no-html-link-for-pages"
	| "next/no-img-element"
	| "next/no-page-custom-font"
	| "next/no-script-component-in-head"
	| "next/no-styled-jsx-in-document"
	| "next/no-sync-scripts"
	| "next/no-title-in-document-head"
	| "next/no-typos"
	| "next/no-unwanted-polyfillio"
>
