= Presets for TypeScript
:experimental:
:source-highlighter: highlight.js

This package provides predefined, opinionated https://www.typescriptlang.org[TypeScript] configuration.

== Installation
Install the `@rainstormy/presets-typescript` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/presets-typescript typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/presets-typescript typescript
----

[source,shell]
----
yarn add --dev @rainstormy/presets-typescript typescript
----

== Usage
Create a https://www.typescriptlang.org/tsconfig[TypeScript configuration file] (`tsconfig.json`) and make it extend the following configurations to enable type-checking and optionally also generation of `js` and `d.ts` files:

* `@rainstormy/presets-typescript/check`
* `@rainstormy/presets-typescript/generate` (to generate `js` and `d.ts` files)
* `@rainstormy/presets-typescript/generate-types` (to generate `d.ts` files only)
* `@rainstormy/presets-typescript/target-node-es2023` (for Node.js projects)
* `@rainstormy/presets-typescript/target-web-es2023` (for web browser projects)

For example:

[source,json]
----
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"extends": [
		"@rainstormy/presets-typescript/check",
		"@rainstormy/presets-typescript/target-web-es2023"
	]
}
----

=== Override Settings
To override the settings configured by this preset, simply specify the desired options.

For example:

[source,json]
----
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"extends": [
		"@rainstormy/presets-typescript/check",
		"@rainstormy/presets-typescript/generate",
		"@rainstormy/presets-typescript/target-node-es2023"
	],
	"compilerOptions": {
		"baseUrl": "./",
		"incremental": true,
		"noEmitOnError": false,
		"outDir": "dist",
		"sourceMap": true
	},
	"include": ["./src/**/*.ts", "./*.config.js", "./*.config.ts"]
}
----
