= Solid Preset for ESLint
:experimental:
:source-highlighter: highlight.js

This package provides a predefined, opinionated https://eslint.org[ESLint] configuration suitable for any https://www.typescriptlang.org[TypeScript]-based web project with https://www.solidjs.com[Solid] components.

This preset configures a subset of rules from the following plugins, which are installed along with the preset package:

* https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules[eslint-plugin-jsx-a11y] (with rule names prefixed by `jsx-a11y/`)
* https://github.com/jsx-eslint/eslint-plugin-react#list-of-supported-rules[eslint-plugin-react] (only for generic JSX rules, with rule names prefixed by `react/`)
* https://github.com/solidjs-community/eslint-plugin-solid#rules[eslint-plugin-solid] (with rule names prefixed by `solid/`)

Additionally, it includes the following preset:

* https://github.com/rainstormy/presets-web/tree/main/packages/presets-eslint-jsx[@rainstormy/presets-eslint-jsx]

== Installation
Install the `@rainstormy/presets-eslint-solid` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/presets-eslint-solid @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/presets-eslint-solid @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
yarn add --dev @rainstormy/presets-eslint-solid @rainstormy/presets-eslint eslint typescript
----

== Usage
Create or extend a https://eslint.org/docs/latest/use/configure/configuration-files-new[flat ESLint configuration file] (`eslint.config.js`) and apply the `eslintPresetSolid` preset.

For example (with the default options in comments):

[source,javascript]
----
import { eslintPresets } from "@rainstormy/presets-eslint"
import { eslintPresetSolid } from "@rainstormy/presets-eslint-solid"

export default eslintPresets({
	additionalPresets: [
		// ...other presets...
		eslintPresetSolid({
			// targetFilePatterns: ["**/*.@(jsx|tsx)"],
		}),
	],
})
----

=== In Combination with Tailwind CSS
For example (with the default options applied):

[source,javascript]
----
import {
	eslintPresetAmbientTypeScriptModules,
	eslintPresets,
} from "@rainstormy/presets-eslint"
import { eslintPresetSolid } from "@rainstormy/presets-eslint-solid"
import { eslintPresetTailwind } from "@rainstormy/presets-eslint-tailwind"

export default eslintPresets({
	additionalPresets: [
		eslintPresetAmbientTypeScriptModules(),
		eslintPresetSolid(),
		eslintPresetTailwind(),
	],
})
----

=== In Combination with Storybook, Testing Library, and Vitest
For example (with the default options applied):

[source,javascript]
----
import {
	eslintPresetAmbientTypeScriptModules,
	eslintPresetTestData,
	eslintPresets,
} from "@rainstormy/presets-eslint"
import { eslintPresetSolid } from "@rainstormy/presets-eslint-solid"
import {
	eslintPresetStorybook,
	eslintPresetStorybookConfiguration,
} from "@rainstormy/presets-eslint-storybook"
import { eslintPresetTestingLibrary } from "@rainstormy/presets-eslint-testing-library"
import { eslintPresetVitest } from "@rainstormy/presets-eslint-vitest"

export default eslintPresets({
	additionalPresets: [
		eslintPresetAmbientTypeScriptModules(),
		eslintPresetSolid(),
		eslintPresetStorybook(),
		eslintPresetStorybookConfiguration(),
		eslintPresetTestData(),
		eslintPresetTestingLibrary(),
		eslintPresetVitest(),
	],
})
----
