= General Preset for ESLint
:experimental:
:source-highlighter: highlight.js

This package provides a predefined, opinionated https://eslint.org[ESLint] configuration suitable for any https://www.typescriptlang.org[TypeScript] project.

== Installation
Install the `@rainstormy/preset-eslint-base` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/preset-eslint-base eslint typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/preset-eslint-base eslint typescript
----

[source,shell]
----
yarn add --dev @rainstormy/preset-eslint-base eslint typescript
----

In addition to the https://eslint.org/docs/latest/rules[built-in rules of ESLint], this preset configures a subset of rules from the following plugins, which are installed along with the preset package:

* https://mysticatea.github.io/eslint-plugin-eslint-comments/rules[eslint-plugin-eslint-comments] (with rule names prefixed by `eslint-comments/`)
* https://github.com/eslint-functional/eslint-plugin-functional#rules[eslint-plugin-functional] (with rule names prefixed by `functional/`)
* https://github.com/import-js/eslint-plugin-import#rules[eslint-plugin-import] (with rule names prefixed by `import/`)
* https://github.com/Limegrass/eslint-plugin-import-alias#configuration[@limegrass/eslint-plugin-import-alias] (with rule names prefixed by `import-alias/`)
* https://github.com/art0rz/eslint-plugin-no-barrel-files#rules[eslint-plugin-no-barrel-files] (with rule names prefixed by `no-barrel-files/`)
* https://github.com/a-tarasyuk/eslint-plugin-redundant-undefined#usage[eslint-plugin-redundant-undefined] (with rule names prefixed by `redundant-undefined/`)
* https://typescript-eslint.io/rules[@typescript-eslint/eslint-plugin] (with rule names prefixed by `typescript/`)
* https://github.com/sindresorhus/eslint-plugin-unicorn#rules[eslint-plugin-unicorn] (with rule names prefixed by `unicorn/`)

== Usage
Create or extend a https://eslint.org/docs/latest/use/configure/configuration-files-new[flat ESLint configuration file] (`eslint.config.js`) to target TypeScript files (and optionally also JavaScript files, e.g. configuration files).
For example:

[source,javascript]
----
import {
	eslintAmbientTypeScriptModules,
	eslintBase
} from "@rainstormy/preset-eslint-base"

export default [
	eslintBase({
		files: ["**/*.+(js|ts|tsx)"],
		tsconfig: "./tsconfig.json",
	}),

	// `eslintAmbientTypeScriptModules` must follow `eslintBase` to take effect.
	eslintAmbientTypeScriptModules({ files: ["**/*.d.ts"] }),
]
----

[TIP]
.Override Rules
====
To override a subset of the rules configured by this preset, add an extra configuration at the end of the array to take precedence over the preset.
For example:

[source,javascript]
----
import {
	eslintAmbientTypeScriptModules,
	eslintBase
} from "@rainstormy/preset-eslint-base"

export default [
	eslintBase({
		files: ["**/*.+(js|ts|tsx)"],
		tsconfig: "./tsconfig.json",
	}),

	// `eslintAmbientTypeScriptModules` and custom configurations must follow `eslintBase` to take effect.
	eslintAmbientTypeScriptModules({ files: ["**/*.d.ts"] }),
	{
		files: ["**/*.+(js|ts|tsx)"],
		rules: {
			"max-lines": "off",
			"prefer-destructuring": "error",
			"typescript/no-magic-numbers": "off",
			"unicorn/prefer-at": "error",
		},
	},
]
----
====

[TIP]
.Ignore Patterns
====
To exclude certain files and directories from linting, add an extra configuration at the beginning of the array.
For example:

[source,javascript]
----
import {
	eslintAmbientTypeScriptModules,
	eslintBase
} from "@rainstormy/preset-eslint-base"

export default [
	{
		ignores: [
			"coverage/**",
			"dist/**",
		],
	},
	eslintBase({
		files: ["**/*.+(js|ts|tsx)"],
		tsconfig: "./tsconfig.json",
	}),

	// `eslintAmbientTypeScriptModules` must follow `eslintBase` to take effect.
	eslintAmbientTypeScriptModules({ files: ["**/*.d.ts"] }),
]
----

Alternatively, you can avoid the need for ignore patterns altogether by explicitly listing the directories you want to include when you run ESLint from the terminal.
For example:

[source,shell]
----
eslint "./src/**/*.{ts,tsx}" "./*.config.{js,ts}" "./*.d.ts"
----
====

== Complementary Presets
* https://github.com/rainstormy/presets-web/tree/main/packages/preset-prettier-base[@rainstormy/preset-prettier-base]
* https://github.com/rainstormy/presets-web/tree/main/packages/preset-typescript[@rainstormy/preset-typescript]
