= General Preset for ESLint
:experimental:
:source-highlighter: highlight.js

This package provides a predefined, opinionated https://eslint.org[ESLint] configuration suitable for any https://www.typescriptlang.org[TypeScript] project.

In addition to the https://eslint.org/docs/latest/rules[built-in rules of ESLint], this preset configures a subset of rules from the following plugins, which are installed along with the preset package:

* https://mysticatea.github.io/eslint-plugin-eslint-comments/rules[eslint-plugin-eslint-comments] (with rule names prefixed by `eslint-comments/`)
* https://github.com/eslint-functional/eslint-plugin-functional#rules[eslint-plugin-functional] (with rule names prefixed by `functional/`)
* https://github.com/import-js/eslint-plugin-import#rules[eslint-plugin-import] (with rule names prefixed by `import/`)
* https://github.com/Limegrass/eslint-plugin-import-alias#configuration[@limegrass/eslint-plugin-import-alias] (with rule names prefixed by `import-alias/`)
* https://github.com/art0rz/eslint-plugin-no-barrel-files#rules[eslint-plugin-no-barrel-files] (with rule names prefixed by `no-barrel-files/`)
* https://github.com/a-tarasyuk/eslint-plugin-redundant-undefined#usage[eslint-plugin-redundant-undefined] (with rule names prefixed by `redundant-undefined/`)
* https://typescript-eslint.io/rules[@typescript-eslint/eslint-plugin] (with rule names prefixed by `typescript/`)
* https://github.com/sindresorhus/eslint-plugin-unicorn#rules[eslint-plugin-unicorn] (with rule names prefixed by `unicorn/`)

== Installation
Install the `@rainstormy/presets-eslint` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
yarn add --dev @rainstormy/presets-eslint eslint typescript
----

== Usage
Create or extend a https://eslint.org/docs/latest/use/configure/configuration-files-new[flat ESLint configuration file] (`eslint.config.js`) and export the result of `eslintPresets` as the configuration object.

For example (with the default options in comments):

[source,javascript]
----
import {
	eslintPresetAmbientTypeScriptModules,
	eslintPresets,
} from "@rainstormy/presets-eslint"

export default eslintPresets({
	// targetFilePatterns: ["**/*.@(js|jsx|ts|tsx)"],
	// tsconfigFiles: "closest-to-each-source-file",
	additionalPresets: [
		eslintPresetAmbientTypeScriptModules({
			// targetFilePatterns: ["**/*.d.ts"],
		}),
	],
})
----

=== Override Rules
To override some rules or to install additional plugins, use the spread syntax (`...`) to add a custom configuration object after the preset configuration object.

For example:

[source,javascript]
----
import { eslintPresets } from "@rainstormy/presets-eslint"

export default [
	...eslintPresets({
		// ...options...
	}),
	{
		files: ["**/*.@(js|jsx|ts|tsx)"],
		rules: {
			"max-lines": "off",
			"prefer-destructuring": "error",
			"typescript/no-magic-numbers": "off",
			"unicorn/prefer-at": "error",
		},
	},
]
----

=== Custom `tsconfig.json` Location
By default, ESLint uses the TypeScript configuration file (`tsconfig.json`) that is located closest to each source file being linted.
Use the `tsconfigFiles` option to specify a different TypeScript configuration file or set of files.

For example:

[source,javascript]
----
import { eslintPresets } from "@rainstormy/presets-eslint"

export default eslintPresets({
	tsconfigFiles: ["./tsconfig.eslint.json"],
	// ...other options...
})
----

=== Ignore Files and Directories
To exclude certain files and directories entirely from linting, use the spread syntax (`...`) to add a custom configuration before the preset configuration object.

For example:

[source,javascript]
----
import { eslintPresets } from "@rainstormy/presets-eslint"

export default [
	{
		ignores: ["coverage/**", "dist/**"],
	},
	...eslintPresets({
		// ...options...
	}),
]
----

Alternatively, you can avoid the need for ignore patterns altogether by explicitly listing the directories you want to include when you run ESLint from the terminal (i.e. opting in to linting instead of opting out).

For example:

[source,shell]
----
eslint "./src/**/*.{ts,tsx}" "./*.config.{js,ts}" "./*.d.ts"
----
