import { type EslintPluginRuleset } from "@rainstormy/presets-eslint/dist/EslintConfig.js"

export type EslintPluginTestingLibraryRuleset = EslintPluginRuleset<
	"testing-library",
	| "testing-library/await-async-events"
	| "testing-library/await-async-queries"
	| "testing-library/await-async-utils"
	| "testing-library/consistent-data-testid"
	| "testing-library/no-await-sync-events"
	| "testing-library/no-await-sync-queries"
	| "testing-library/no-container"
	| "testing-library/no-debugging-utils"
	| "testing-library/no-dom-import"
	| "testing-library/no-global-regexp-flag-in-query"
	| "testing-library/no-manual-cleanup"
	| "testing-library/no-node-access"
	| "testing-library/no-promise-in-fire-event"
	| "testing-library/no-render-in-lifecycle"
	| "testing-library/no-unnecessary-act"
	| "testing-library/no-wait-for-multiple-assertions"
	| "testing-library/no-wait-for-side-effects"
	| "testing-library/no-wait-for-snapshot"
	| "testing-library/prefer-explicit-assert"
	| "testing-library/prefer-find-by"
	| "testing-library/prefer-implicit-assert"
	| "testing-library/prefer-presence-queries"
	| "testing-library/prefer-query-by-disappearance"
	| "testing-library/prefer-query-matchers"
	| "testing-library/prefer-screen-queries"
	| "testing-library/prefer-user-event"
	| "testing-library/render-result-naming-convention"
>
