= Preact Preset for ESLint
:experimental:
:source-highlighter: highlight.js

This package provides a predefined, opinionated https://eslint.org[ESLint] configuration suitable for any https://www.typescriptlang.org[TypeScript]-based web project with https://preactjs.com[Preact] components.

This preset configures a subset of rules from the following plugins, which are installed along with the preset package:

* https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules[eslint-plugin-jsx-a11y] (with rule names prefixed by `accessibility/`)
* https://github.com/jsx-eslint/eslint-plugin-react#list-of-supported-rules[eslint-plugin-react] (with rule names prefixed by `react/`)
* https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks#custom-configuration[eslint-plugin-react-hooks] (with rule names prefixed by `react-hooks/`)

Additionally, it includes the following presets:

* https://github.com/rainstormy/presets-web/tree/main/packages/presets-eslint-jsx[@rainstormy/presets-eslint-jsx]
* https://github.com/rainstormy/presets-web/tree/main/packages/presets-eslint-react[@rainstormy/presets-eslint-react]

== Installation
Install the `@rainstormy/presets-eslint-preact` package and its peer dependencies:

[source,shell]
----
npm install --save-dev @rainstormy/presets-eslint-preact @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
pnpm install --save-dev @rainstormy/presets-eslint-preact @rainstormy/presets-eslint eslint typescript
----

[source,shell]
----
yarn add --dev @rainstormy/presets-eslint-preact @rainstormy/presets-eslint eslint typescript
----

== Usage
Create or extend a https://eslint.org/docs/latest/use/configure/configuration-files-new[flat ESLint configuration file] (`eslint.config.js`) and apply the `eslintPresetPreact` preset.

For example (with the default options in comments):

[source,javascript]
----
import { eslintPresets } from "@rainstormy/presets-eslint"
import { eslintPresetPreact } from "@rainstormy/presets-eslint-preact"

export default eslintPresets({
	additionalPresets: [
		// ...other presets...
		eslintPresetPreact({
			// targetFilePatterns: ["**/*.@(jsx|tsx)"],
		}),
	],
})
----

=== In Combination with Tailwind CSS
For example (with the default options applied):

[source,javascript]
----
import {
	eslintPresetAmbientTypescriptModules,
	eslintPresets,
} from "@rainstormy/presets-eslint"
import { eslintPresetPreact } from "@rainstormy/presets-eslint-preact"
import { eslintPresetTailwind } from "@rainstormy/presets-eslint-tailwind"

export default eslintPresets({
	additionalPresets: [
		eslintPresetAmbientTypescriptModules(),
		eslintPresetPreact(),
		eslintPresetTailwind(),
	],
})
----

=== In Combination with Storybook, Testing Library, and Vitest
For example (with the default options applied):

[source,javascript]
----
import {
	eslintPresetAmbientTypescriptModules,
	eslintPresetTestData,
	eslintPresets,
} from "@rainstormy/presets-eslint"
import { eslintPresetPreact } from "@rainstormy/presets-eslint-preact"
import {
	eslintPresetStorybook,
	eslintPresetStorybookConfiguration,
} from "@rainstormy/presets-eslint-storybook"
import { eslintPresetTestingLibrary } from "@rainstormy/presets-eslint-testing-library"
import { eslintPresetVitest } from "@rainstormy/presets-eslint-vitest"

export default eslintPresets({
	additionalPresets: [
		eslintPresetAmbientTypescriptModules(),
		eslintPresetPreact(),
		eslintPresetStorybook(),
		eslintPresetStorybookConfiguration(),
		eslintPresetTestData(),
		eslintPresetTestingLibrary(),
		eslintPresetVitest(),
	],
})
----
