# This workflow publishes the package to the npm registry.
#
# It is triggered automatically by pushing a Git tag with a `v` prefix, as done by the `release-tag.yml` workflow.
#
# It can be triggered manually via the GitHub CLI:
#   gh workflow run release-npm.yml --ref <tag-name>
#   gh run watch
#
# It can be triggered manually via the GitHub web interface:
#   https://github.com/rainstormy/presets-web/actions/workflows/release-npm.yml

name: Release / npm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: release-npm-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  quality-assurance:
    name: Quality assurance
    permissions:
      contents: read # Allow the job to call the reusable `ci.yml` workflow.
      pull-requests: read # `ci.yml` requires `pull-requests` read permissions.
    uses: ./.github/workflows/ci.yml

  npm-package:
    strategy:
      fail-fast: true
      matrix:
        package-name:
          - presets-biome
          - presets-typescript
    name: 'npm package: @rainstormy/${{ matrix.package-name }}'
    needs: quality-assurance
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: read # Allow the job to check out the repository.
      id-token: write # Allow npm to publish the package with provenance.
    steps:
      - name: Check out the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # https://github.com/actions/checkout/releases/tag/v4.1.5
        #
      - name: Restore build artifacts
        uses: ./.github/actions/build-artifacts
        #
      - name: Install pnpm and third-party dependencies
        uses: ./.github/actions/pnpm
        #
      - name: Publish the package to npm
        uses: rainstormy-actions/release/npm@f27c642f46a7c4c6125f6714756305420007537f # https://github.com/rainstormy-actions/release/releases/tag/v1.0.0
        with:
          access-level: public
          npm-auth-token: ${{ secrets.BOT_NIMBUS_NPM_TOKEN }}
          packagejson-path: packages/${{ matrix.package-name }}/package.json
